import type { GatewayMethodDescriptor } from './method-catalog-shared.ts';
import { GENERIC_OBJECT_SCHEMA,EMPTY_OBJECT_SCHEMA,STRING_SCHEMA,NUMBER_SCHEMA,arraySchema,objectSchema,listOutputSchema,entityOutputSchema,actionResultOutputSchema,bodyEnvelopeSchema,methodDescriptor,runtimeEventId } from './method-catalog-shared.ts';

export const builtinGatewayControlMethodDescriptors: readonly GatewayMethodDescriptor[] = [
  methodDescriptor({
    id: 'control.status',
    title: 'Daemon Status',
    description: 'Return daemon status and version.',
    category: 'control-plane',
    scopes: ['read:control-plane'],
    http: { method: 'GET', path: '/status' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: objectSchema({
      status: STRING_SCHEMA,
      version: STRING_SCHEMA,
    }, ['status', 'version'], { additionalProperties: true }),
  }),
  methodDescriptor({
    id: 'control.snapshot',
    title: 'Control-Plane Snapshot',
    description: 'Return the current control-plane gateway snapshot.',
    category: 'control-plane',
    scopes: ['read:control-plane'],
    http: { method: 'GET', path: '/api/control-plane' },
    events: [runtimeEventId('control-plane')],
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'control.web',
    title: 'Control-Plane Web Shell',
    description: 'Return the built-in control-plane HTML shell for external clients.',
    category: 'control-plane',
    scopes: ['read:control-plane'],
    transport: ['http'],
    http: { method: 'GET', path: '/api/control-plane/web' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: objectSchema({ html: STRING_SCHEMA }, ['html']),
    invokable: false,
    metadata: { responseKind: 'html' },
  }),
  methodDescriptor({
    id: 'control.messages.list',
    title: 'List Control-Plane Messages',
    description: 'Return recent surface messages published through the control plane.',
    category: 'control-plane',
    scopes: ['read:control-plane'],
    http: { method: 'GET', path: '/api/control-plane/messages' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: listOutputSchema('messages'),
  }),
  methodDescriptor({
    id: 'control.clients.list',
    title: 'List Control-Plane Clients',
    description: 'Return authenticated and recently connected control-plane clients.',
    category: 'control-plane',
    scopes: ['read:control-plane'],
    http: { method: 'GET', path: '/api/control-plane/clients' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: listOutputSchema('clients'),
  }),
  methodDescriptor({
    id: 'control.methods.list',
    title: 'List Gateway Methods',
    description: 'Return the gateway method catalog.',
    category: 'control-plane',
    scopes: ['read:control-plane'],
    http: { method: 'GET', path: '/api/control-plane/methods' },
    inputSchema: objectSchema({
      category: STRING_SCHEMA,
      source: STRING_SCHEMA,
    }),
    outputSchema: listOutputSchema('methods'),
  }),
  methodDescriptor({
    id: 'control.methods.get',
    title: 'Get Gateway Method',
    description: 'Return a single gateway method descriptor.',
    category: 'control-plane',
    scopes: ['read:control-plane'],
    http: { method: 'GET', path: '/api/control-plane/methods/{methodId}' },
    inputSchema: objectSchema({
      methodId: STRING_SCHEMA,
    }, ['methodId']),
    outputSchema: entityOutputSchema('method'),
  }),
  methodDescriptor({
    id: 'control.events.catalog',
    title: 'List Gateway Events',
    description: 'Return the event catalog for SSE and WebSocket control-plane subscriptions.',
    category: 'control-plane',
    scopes: ['read:control-plane', 'read:events'],
    http: { method: 'GET', path: '/api/control-plane/events/catalog' },
    inputSchema: objectSchema({
      category: STRING_SCHEMA,
      domain: STRING_SCHEMA,
    }),
    outputSchema: listOutputSchema('events'),
  }),
  methodDescriptor({
    id: 'control.events.stream',
    title: 'Open Control-Plane Event Stream',
    description: 'Open the SSE control-plane event stream.',
    category: 'control-plane',
    scopes: ['read:events'],
    transport: ['http'],
    http: { method: 'GET', path: '/api/control-plane/events' },
    inputSchema: objectSchema({
      domains: STRING_SCHEMA,
    }),
    outputSchema: objectSchema({
      contentType: STRING_SCHEMA,
      mode: STRING_SCHEMA,
    }, ['contentType', 'mode']),
    invokable: false,
    metadata: { responseKind: 'sse', stream: true },
  }),
  methodDescriptor({
    id: 'review.snapshot',
    title: 'Review Snapshot',
    description: 'Return the integration review snapshot used by external helpers.',
    category: 'review',
    scopes: ['read:automation'],
    http: { method: 'GET', path: '/api/review' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'sessions.integration.snapshot',
    title: 'Legacy Session Snapshot',
    description: 'Return the legacy integration session snapshot.',
    category: 'sessions',
    scopes: ['read:sessions'],
    http: { method: 'GET', path: '/api/session' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'sessions.list',
    title: 'List Shared Sessions',
    description: 'Return shared-session integration state.',
    category: 'sessions',
    scopes: ['read:sessions'],
    http: { method: 'GET', path: '/api/sessions' },
    events: [runtimeEventId('session')],
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'sessions.create',
    title: 'Create Shared Session',
    description: 'Create a shared session for a surface, route, or web client.',
    category: 'sessions',
    scopes: ['write:sessions'],
    http: { method: 'POST', path: '/api/sessions' },
    inputSchema: bodyEnvelopeSchema({
      title: STRING_SCHEMA,
      surfaceKind: STRING_SCHEMA,
      surfaceId: STRING_SCHEMA,
    }),
    outputSchema: actionResultOutputSchema('session'),
  }),
  methodDescriptor({
    id: 'sessions.get',
    title: 'Get Shared Session',
    description: 'Return metadata for a shared session.',
    category: 'sessions',
    scopes: ['read:sessions'],
    http: { method: 'GET', path: '/api/sessions/{sessionId}' },
    inputSchema: objectSchema({ sessionId: STRING_SCHEMA }, ['sessionId']),
    outputSchema: actionResultOutputSchema('session'),
  }),
  methodDescriptor({
    id: 'sessions.close',
    title: 'Close Shared Session',
    description: 'Mark a shared session as closed.',
    category: 'sessions',
    scopes: ['write:sessions'],
    http: { method: 'POST', path: '/api/sessions/{sessionId}/close' },
    inputSchema: objectSchema({ sessionId: STRING_SCHEMA }, ['sessionId']),
    outputSchema: actionResultOutputSchema('session'),
  }),
  methodDescriptor({
    id: 'sessions.reopen',
    title: 'Reopen Shared Session',
    description: 'Reopen a previously closed shared session.',
    category: 'sessions',
    scopes: ['write:sessions'],
    http: { method: 'POST', path: '/api/sessions/{sessionId}/reopen' },
    inputSchema: objectSchema({ sessionId: STRING_SCHEMA }, ['sessionId']),
    outputSchema: actionResultOutputSchema('session'),
  }),
  methodDescriptor({
    id: 'sessions.messages.list',
    title: 'List Shared Session Messages',
    description: 'Return message history for a shared session.',
    category: 'sessions',
    scopes: ['read:sessions'],
    http: { method: 'GET', path: '/api/sessions/{sessionId}/messages' },
    inputSchema: objectSchema({
      sessionId: STRING_SCHEMA,
      limit: NUMBER_SCHEMA,
      before: STRING_SCHEMA,
    }, ['sessionId']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'sessions.messages.create',
    title: 'Post Shared Session Message',
    description: 'Append a user message to a shared session and queue assistant work.',
    category: 'sessions',
    scopes: ['write:sessions'],
    http: { method: 'POST', path: '/api/sessions/{sessionId}/messages' },
    inputSchema: bodyEnvelopeSchema({
      body: STRING_SCHEMA,
      surfaceKind: STRING_SCHEMA,
      surfaceId: STRING_SCHEMA,
    }, ['body']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'tasks.list',
    title: 'List Runtime Tasks',
    description: 'Return the integration snapshot for runtime tasks.',
    category: 'tasks',
    scopes: ['read:tasks'],
    http: { method: 'GET', path: '/api/tasks' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'tasks.create',
    title: 'Create Task',
    description: 'Submit a task to the daemon or a shared session.',
    category: 'tasks',
    scopes: ['write:tasks'],
    http: { method: 'POST', path: '/task' },
    events: [runtimeEventId('tasks')],
    inputSchema: GENERIC_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'tasks.get',
    title: 'Get Runtime Task',
    description: 'Return a single runtime task record.',
    category: 'tasks',
    scopes: ['read:tasks'],
    http: { method: 'GET', path: '/api/tasks/{taskId}' },
    inputSchema: objectSchema({ taskId: STRING_SCHEMA }, ['taskId']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'tasks.cancel',
    title: 'Cancel Runtime Task',
    description: 'Cancel an in-flight runtime task.',
    category: 'tasks',
    scopes: ['write:tasks'],
    http: { method: 'POST', path: '/api/tasks/{taskId}/cancel' },
    inputSchema: objectSchema({ taskId: STRING_SCHEMA }, ['taskId']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'tasks.retry',
    title: 'Retry Runtime Task',
    description: 'Retry a runtime task through the task action endpoint.',
    category: 'tasks',
    scopes: ['write:tasks'],
    http: { method: 'POST', path: '/api/tasks/{taskId}/retry' },
    inputSchema: objectSchema({ taskId: STRING_SCHEMA }, ['taskId']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'tasks.status',
    title: 'Get Task Status',
    description: 'Return lightweight runtime task status by agent id.',
    category: 'tasks',
    scopes: ['read:tasks'],
    http: { method: 'GET', path: '/task/{agentId}' },
    inputSchema: objectSchema({ agentId: STRING_SCHEMA }, ['agentId']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'automation.integration.snapshot',
    title: 'Automation Integration Snapshot',
    description: 'Return the legacy integration automation snapshot.',
    category: 'automation',
    scopes: ['read:automation'],
    http: { method: 'GET', path: '/api/automation' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'automation.jobs.list',
    title: 'List Automation Jobs',
    description: 'Return automation jobs and recent runs.',
    category: 'automation',
    scopes: ['read:automation'],
    http: { method: 'GET', path: '/api/automation/jobs' },
    events: [runtimeEventId('automation')],
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'automation.jobs.create',
    title: 'Create Automation Job',
    description: 'Create a durable automation job.',
    category: 'automation',
    scopes: ['write:automation'],
    http: { method: 'POST', path: '/api/automation/jobs' },
    events: [runtimeEventId('automation')],
    inputSchema: GENERIC_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'automation.jobs.patch',
    title: 'Patch Automation Job',
    description: 'Patch a durable automation job.',
    category: 'automation',
    scopes: ['write:automation'],
    http: { method: 'PATCH', path: '/api/automation/jobs/{jobId}' },
    events: [runtimeEventId('automation')],
    inputSchema: GENERIC_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'automation.jobs.delete',
    title: 'Delete Automation Job',
    description: 'Delete a durable automation job.',
    category: 'automation',
    scopes: ['write:automation'],
    http: { method: 'DELETE', path: '/api/automation/jobs/{jobId}' },
    events: [runtimeEventId('automation')],
    inputSchema: objectSchema({ jobId: STRING_SCHEMA }, ['jobId']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
    dangerous: true,
  }),
  methodDescriptor({
    id: 'automation.jobs.enable',
    title: 'Enable Automation Job',
    description: 'Enable a durable automation job.',
    category: 'automation',
    scopes: ['write:automation'],
    http: { method: 'POST', path: '/api/automation/jobs/{jobId}/enable' },
    events: [runtimeEventId('automation')],
    inputSchema: objectSchema({ jobId: STRING_SCHEMA }, ['jobId']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'automation.jobs.disable',
    title: 'Disable Automation Job',
    description: 'Disable a durable automation job.',
    category: 'automation',
    scopes: ['write:automation'],
    http: { method: 'POST', path: '/api/automation/jobs/{jobId}/disable' },
    events: [runtimeEventId('automation')],
    inputSchema: objectSchema({ jobId: STRING_SCHEMA }, ['jobId']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'automation.jobs.pause',
    title: 'Pause Automation Job',
    description: 'Pause a durable automation job.',
    category: 'automation',
    scopes: ['write:automation'],
    http: { method: 'POST', path: '/api/automation/jobs/{jobId}/pause' },
    events: [runtimeEventId('automation')],
    inputSchema: objectSchema({ jobId: STRING_SCHEMA }, ['jobId']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'automation.jobs.resume',
    title: 'Resume Automation Job',
    description: 'Resume a durable automation job.',
    category: 'automation',
    scopes: ['write:automation'],
    http: { method: 'POST', path: '/api/automation/jobs/{jobId}/resume' },
    events: [runtimeEventId('automation')],
    inputSchema: objectSchema({ jobId: STRING_SCHEMA }, ['jobId']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'automation.jobs.run',
    title: 'Run Automation Job Now',
    description: 'Trigger an automation job immediately.',
    category: 'automation',
    scopes: ['write:automation'],
    http: { method: 'POST', path: '/api/automation/jobs/{jobId}/run' },
    events: [runtimeEventId('automation')],
    inputSchema: objectSchema({ jobId: STRING_SCHEMA }, ['jobId']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'automation.runs.list',
    title: 'List Automation Runs',
    description: 'Return automation run history.',
    category: 'automation',
    scopes: ['read:automation'],
    http: { method: 'GET', path: '/api/automation/runs' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'automation.runs.get',
    title: 'Get Automation Run',
    description: 'Return a single automation run record.',
    category: 'automation',
    scopes: ['read:automation'],
    http: { method: 'GET', path: '/api/automation/runs/{runId}' },
    inputSchema: objectSchema({ runId: STRING_SCHEMA }, ['runId']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'automation.runs.cancel',
    title: 'Cancel Automation Run',
    description: 'Cancel an active automation run.',
    category: 'automation',
    scopes: ['write:automation'],
    http: { method: 'POST', path: '/api/automation/runs/{runId}/cancel' },
    inputSchema: objectSchema({ runId: STRING_SCHEMA }, ['runId']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'automation.runs.retry',
    title: 'Retry Automation Run',
    description: 'Retry a completed or failed automation run.',
    category: 'automation',
    scopes: ['write:automation'],
    http: { method: 'POST', path: '/api/automation/runs/{runId}/retry' },
    inputSchema: objectSchema({ runId: STRING_SCHEMA }, ['runId']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'automation.heartbeat.list',
    title: 'List Automation Heartbeat Queue',
    description: 'Return automation jobs queued for the next heartbeat.',
    category: 'automation',
    scopes: ['read:automation'],
    http: { method: 'GET', path: '/api/automation/heartbeat' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: objectSchema({ pending: arraySchema(GENERIC_OBJECT_SCHEMA) }, ['pending']),
  }),
  methodDescriptor({
    id: 'automation.heartbeat.run',
    title: 'Run Automation Heartbeat',
    description: 'Process automation jobs queued for the next heartbeat.',
    category: 'automation',
    scopes: ['write:automation'],
    http: { method: 'POST', path: '/api/automation/heartbeat' },
    events: [runtimeEventId('automation')],
    inputSchema: bodyEnvelopeSchema({ source: STRING_SCHEMA }),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'deliveries.list',
    title: 'List Deliveries',
    description: 'Return delivery records and integration snapshot data.',
    category: 'deliveries',
    scopes: ['read:deliveries'],
    http: { method: 'GET', path: '/api/deliveries' },
    events: [runtimeEventId('deliveries')],
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'deliveries.get',
    title: 'Get Delivery',
    description: 'Return a single delivery record.',
    category: 'deliveries',
    scopes: ['read:deliveries'],
    http: { method: 'GET', path: '/api/deliveries/{deliveryId}' },
    inputSchema: objectSchema({ deliveryId: STRING_SCHEMA }, ['deliveryId']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'schedules.list',
    title: 'List Schedules',
    description: 'Return legacy schedule records.',
    category: 'automation',
    scopes: ['read:automation'],
    http: { method: 'GET', path: '/schedules' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'schedules.create',
    title: 'Create Schedule',
    description: 'Create a legacy schedule record.',
    category: 'automation',
    scopes: ['write:automation'],
    http: { method: 'POST', path: '/schedules' },
    inputSchema: GENERIC_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'schedules.delete',
    title: 'Delete Schedule',
    description: 'Delete a legacy schedule record.',
    category: 'automation',
    scopes: ['write:automation'],
    http: { method: 'DELETE', path: '/schedules/{scheduleId}' },
    inputSchema: objectSchema({ scheduleId: STRING_SCHEMA }, ['scheduleId']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
    dangerous: true,
  }),
  methodDescriptor({
    id: 'schedules.enable',
    title: 'Enable Schedule',
    description: 'Enable a legacy schedule record.',
    category: 'automation',
    scopes: ['write:automation'],
    http: { method: 'POST', path: '/schedules/{scheduleId}/enable' },
    inputSchema: objectSchema({ scheduleId: STRING_SCHEMA }, ['scheduleId']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'schedules.disable',
    title: 'Disable Schedule',
    description: 'Disable a legacy schedule record.',
    category: 'automation',
    scopes: ['write:automation'],
    http: { method: 'POST', path: '/schedules/{scheduleId}/disable' },
    inputSchema: objectSchema({ scheduleId: STRING_SCHEMA }, ['scheduleId']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'schedules.run',
    title: 'Run Schedule Now',
    description: 'Trigger a legacy schedule immediately.',
    category: 'automation',
    scopes: ['write:automation'],
    http: { method: 'POST', path: '/schedules/{scheduleId}/run' },
    inputSchema: objectSchema({ scheduleId: STRING_SCHEMA }, ['scheduleId']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'routes.snapshot',
    title: 'Route Snapshot',
    description: 'Return the route and binding integration snapshot.',
    category: 'routes',
    scopes: ['read:routes'],
    http: { method: 'GET', path: '/api/routes' },
    events: [runtimeEventId('routes')],
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'surfaces.list',
    title: 'List Surfaces',
    description: 'Return registered channel and control surfaces.',
    category: 'routes',
    scopes: ['read:routes'],
    http: { method: 'GET', path: '/api/surfaces' },
    events: [runtimeEventId('surfaces')],
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: listOutputSchema('surfaces'),
  }),
  methodDescriptor({
    id: 'routes.bindings.list',
    title: 'List Route Bindings',
    description: 'Return configured route bindings.',
    category: 'routes',
    scopes: ['read:routes'],
    http: { method: 'GET', path: '/api/routes/bindings' },
    events: [runtimeEventId('routes')],
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: listOutputSchema('bindings'),
  }),
  methodDescriptor({
    id: 'routes.bindings.create',
    title: 'Create Route Binding',
    description: 'Create or upsert a route binding.',
    category: 'routes',
    scopes: ['write:routes'],
    access: 'admin',
    http: { method: 'POST', path: '/api/routes/bindings' },
    events: [runtimeEventId('routes')],
    inputSchema: GENERIC_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'routes.bindings.patch',
    title: 'Patch Route Binding',
    description: 'Patch an existing route binding.',
    category: 'routes',
    scopes: ['write:routes'],
    access: 'admin',
    http: { method: 'PATCH', path: '/api/routes/bindings/{bindingId}' },
    events: [runtimeEventId('routes')],
    inputSchema: GENERIC_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'routes.bindings.delete',
    title: 'Delete Route Binding',
    description: 'Delete an existing route binding.',
    category: 'routes',
    scopes: ['write:routes'],
    access: 'admin',
    http: { method: 'DELETE', path: '/api/routes/bindings/{bindingId}' },
    events: [runtimeEventId('routes')],
    inputSchema: objectSchema({ bindingId: STRING_SCHEMA }, ['bindingId']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
    dangerous: true,
  }),
  methodDescriptor({
    id: 'approvals.list',
    title: 'List Approvals',
    description: 'Return pending and historical approval records.',
    category: 'approvals',
    scopes: ['read:approvals'],
    http: { method: 'GET', path: '/api/approvals' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'approvals.claim',
    title: 'Claim Approval',
    description: 'Claim a pending approval for operator handling.',
    category: 'approvals',
    scopes: ['write:approvals'],
    http: { method: 'POST', path: '/api/approvals/{approvalId}/claim' },
    inputSchema: objectSchema({ approvalId: STRING_SCHEMA }, ['approvalId']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'approvals.approve',
    title: 'Approve Approval',
    description: 'Approve a pending approval.',
    category: 'approvals',
    scopes: ['write:approvals'],
    http: { method: 'POST', path: '/api/approvals/{approvalId}/approve' },
    inputSchema: GENERIC_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'approvals.deny',
    title: 'Deny Approval',
    description: 'Deny a pending approval.',
    category: 'approvals',
    scopes: ['write:approvals'],
    http: { method: 'POST', path: '/api/approvals/{approvalId}/deny' },
    inputSchema: GENERIC_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'approvals.cancel',
    title: 'Cancel Approval',
    description: 'Cancel a pending approval.',
    category: 'approvals',
    scopes: ['write:approvals'],
    http: { method: 'POST', path: '/api/approvals/{approvalId}/cancel' },
    inputSchema: GENERIC_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
];
