import type { GatewayMethodDescriptor } from './method-catalog-shared.ts';
import { GENERIC_OBJECT_SCHEMA,EMPTY_OBJECT_SCHEMA,STRING_SCHEMA,BOOLEAN_SCHEMA,NUMBER_SCHEMA,objectSchema,listOutputSchema,entityOutputSchema,bodyEnvelopeSchema,methodDescriptor,runtimeEventId } from './method-catalog-shared.ts';

export const builtinGatewayKnowledgeMethodDescriptors: readonly GatewayMethodDescriptor[] = [
  methodDescriptor({
    id: 'knowledge.status',
    title: 'Knowledge Status',
    description: 'Return structured knowledge runtime status and record counts.',
    category: 'knowledge',
    scopes: ['read:knowledge'],
    http: { method: 'GET', path: '/api/knowledge/status' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'knowledge.sources.list',
    title: 'List Knowledge Sources',
    description: 'Return ingested structured knowledge sources.',
    category: 'knowledge',
    scopes: ['read:knowledge'],
    http: { method: 'GET', path: '/api/knowledge/sources' },
    inputSchema: objectSchema({ limit: NUMBER_SCHEMA }),
    outputSchema: listOutputSchema('sources'),
  }),
  methodDescriptor({
    id: 'knowledge.nodes.list',
    title: 'List Knowledge Nodes',
    description: 'Return compiled knowledge nodes.',
    category: 'knowledge',
    scopes: ['read:knowledge'],
    http: { method: 'GET', path: '/api/knowledge/nodes' },
    inputSchema: objectSchema({ limit: NUMBER_SCHEMA }),
    outputSchema: listOutputSchema('nodes'),
  }),
  methodDescriptor({
    id: 'knowledge.issues.list',
    title: 'List Knowledge Issues',
    description: 'Return current knowledge lint and health issues.',
    category: 'knowledge',
    scopes: ['read:knowledge'],
    http: { method: 'GET', path: '/api/knowledge/issues' },
    inputSchema: objectSchema({ limit: NUMBER_SCHEMA }),
    outputSchema: listOutputSchema('issues'),
  }),
  methodDescriptor({
    id: 'knowledge.item.get',
    title: 'Get Knowledge Item',
    description: 'Return a single structured knowledge source, node, or issue with linked relations.',
    category: 'knowledge',
    scopes: ['read:knowledge'],
    http: { method: 'GET', path: '/api/knowledge/items/{id}' },
    inputSchema: objectSchema({ id: STRING_SCHEMA }, ['id']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'knowledge.connectors.list',
    title: 'List Knowledge Connectors',
    description: 'Return discoverable knowledge ingest connectors with input metadata and examples.',
    category: 'knowledge',
    scopes: ['read:knowledge'],
    http: { method: 'GET', path: '/api/knowledge/connectors' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: listOutputSchema('connectors'),
  }),
  methodDescriptor({
    id: 'knowledge.connector.doctor',
    title: 'Doctor Knowledge Connector',
    description: 'Return readiness and setup diagnostics for a knowledge connector.',
    category: 'knowledge',
    scopes: ['read:knowledge'],
    http: { method: 'GET', path: '/api/knowledge/connectors/{id}/doctor' },
    inputSchema: objectSchema({ id: STRING_SCHEMA }, ['id']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'knowledge.connector.get',
    title: 'Get Knowledge Connector',
    description: 'Return a single knowledge connector manifest.',
    category: 'knowledge',
    scopes: ['read:knowledge'],
    http: { method: 'GET', path: '/api/knowledge/connectors/{id}' },
    inputSchema: objectSchema({ id: STRING_SCHEMA }, ['id']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'knowledge.ingest.url',
    title: 'Ingest URL Into Knowledge',
    description: 'Fetch, snapshot, and compile a URL into the structured knowledge store.',
    category: 'knowledge',
    scopes: ['write:knowledge'],
    access: 'admin',
    http: { method: 'POST', path: '/api/knowledge/ingest/url' },
    inputSchema: bodyEnvelopeSchema({ url: STRING_SCHEMA }, ['url']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'knowledge.ingest.bookmarks',
    title: 'Import Bookmark File',
    description: 'Parse a bookmark export file and ingest its URLs into the structured knowledge store.',
    category: 'knowledge',
    scopes: ['write:knowledge'],
    access: 'admin',
    http: { method: 'POST', path: '/api/knowledge/ingest/bookmarks' },
    inputSchema: bodyEnvelopeSchema({ path: STRING_SCHEMA }, ['path']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'knowledge.ingest.urls',
    title: 'Import URL List',
    description: 'Parse a URL list file and ingest its entries into the structured knowledge store.',
    category: 'knowledge',
    scopes: ['write:knowledge'],
    access: 'admin',
    http: { method: 'POST', path: '/api/knowledge/ingest/urls' },
    inputSchema: bodyEnvelopeSchema({ path: STRING_SCHEMA }, ['path']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'knowledge.ingest.connector',
    title: 'Ingest Connector Input',
    description: 'Resolve a knowledge connector against inline input, inline content, or file-backed content.',
    category: 'knowledge',
    scopes: ['write:knowledge'],
    access: 'admin',
    http: { method: 'POST', path: '/api/knowledge/ingest/connector' },
    inputSchema: bodyEnvelopeSchema({ connectorId: STRING_SCHEMA }, ['connectorId']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'knowledge.ingest.artifact',
    title: 'Ingest Artifact Into Knowledge',
    description: 'Snapshot a local path, remote URI, or existing artifact into the structured knowledge store and run structured extraction.',
    category: 'knowledge',
    scopes: ['write:knowledge'],
    access: 'admin',
    http: { method: 'POST', path: '/api/knowledge/ingest/artifact' },
    events: [runtimeEventId('knowledge')],
    inputSchema: bodyEnvelopeSchema({}),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'knowledge.search',
    title: 'Search Structured Knowledge',
    description: 'Search structured knowledge sources and nodes with compact ranked results.',
    category: 'knowledge',
    scopes: ['read:knowledge'],
    http: { method: 'POST', path: '/api/knowledge/search' },
    inputSchema: bodyEnvelopeSchema({ query: STRING_SCHEMA }, ['query']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'knowledge.extractions.list',
    title: 'List Knowledge Extractions',
    description: 'Return structured extraction records for ingested sources.',
    category: 'knowledge',
    scopes: ['read:knowledge'],
    http: { method: 'GET', path: '/api/knowledge/extractions' },
    inputSchema: objectSchema({ limit: NUMBER_SCHEMA, sourceId: STRING_SCHEMA }),
    outputSchema: listOutputSchema('extractions'),
  }),
  methodDescriptor({
    id: 'knowledge.extraction.get',
    title: 'Get Knowledge Extraction',
    description: 'Return a single knowledge extraction record.',
    category: 'knowledge',
    scopes: ['read:knowledge'],
    http: { method: 'GET', path: '/api/knowledge/extractions/{id}' },
    inputSchema: objectSchema({ id: STRING_SCHEMA }, ['id']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'knowledge.source.extraction.get',
    title: 'Get Source Extraction',
    description: 'Return the structured extraction record for a single knowledge source.',
    category: 'knowledge',
    scopes: ['read:knowledge'],
    http: { method: 'GET', path: '/api/knowledge/sources/{id}/extraction' },
    inputSchema: objectSchema({ id: STRING_SCHEMA }, ['id']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'knowledge.packet',
    title: 'Build Knowledge Packet',
    description: 'Build a compact structured knowledge packet for a task and write scope.',
    category: 'knowledge',
    scopes: ['read:knowledge'],
    http: { method: 'POST', path: '/api/knowledge/packet' },
    inputSchema: bodyEnvelopeSchema({ task: STRING_SCHEMA }, ['task']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'knowledge.usage.list',
    title: 'List Knowledge Usage',
    description: 'Return the recent knowledge usage ledger for packet hits, search hits, and item inspection.',
    category: 'knowledge',
    scopes: ['read:knowledge'],
    http: { method: 'GET', path: '/api/knowledge/usage' },
    inputSchema: objectSchema({ limit: NUMBER_SCHEMA, targetKind: STRING_SCHEMA, targetId: STRING_SCHEMA, usageKind: STRING_SCHEMA }),
    outputSchema: listOutputSchema('usage'),
  }),
  methodDescriptor({
    id: 'knowledge.candidates.list',
    title: 'List Consolidation Candidates',
    description: 'Return scored consolidation candidates for durable memory promotion, review, or source refresh.',
    category: 'knowledge',
    scopes: ['read:knowledge'],
    http: { method: 'GET', path: '/api/knowledge/candidates' },
    inputSchema: objectSchema({ limit: NUMBER_SCHEMA, status: STRING_SCHEMA, subjectKind: STRING_SCHEMA, subjectId: STRING_SCHEMA }),
    outputSchema: listOutputSchema('candidates'),
  }),
  methodDescriptor({
    id: 'knowledge.candidate.get',
    title: 'Get Consolidation Candidate',
    description: 'Return a single consolidation candidate.',
    category: 'knowledge',
    scopes: ['read:knowledge'],
    http: { method: 'GET', path: '/api/knowledge/candidates/{id}' },
    inputSchema: objectSchema({ id: STRING_SCHEMA }, ['id']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'knowledge.candidate.decide',
    title: 'Decide Consolidation Candidate',
    description: 'Accept, reject, or supersede a knowledge consolidation candidate.',
    category: 'knowledge',
    scopes: ['write:knowledge'],
    access: 'admin',
    http: { method: 'POST', path: '/api/knowledge/candidates/{id}/decide' },
    inputSchema: bodyEnvelopeSchema({ decision: STRING_SCHEMA }, ['decision']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'knowledge.reports.list',
    title: 'List Consolidation Reports',
    description: 'Return deterministic knowledge consolidation reports.',
    category: 'knowledge',
    scopes: ['read:knowledge'],
    http: { method: 'GET', path: '/api/knowledge/reports' },
    inputSchema: objectSchema({ limit: NUMBER_SCHEMA }),
    outputSchema: listOutputSchema('reports'),
  }),
  methodDescriptor({
    id: 'knowledge.report.get',
    title: 'Get Consolidation Report',
    description: 'Return a single knowledge consolidation report.',
    category: 'knowledge',
    scopes: ['read:knowledge'],
    http: { method: 'GET', path: '/api/knowledge/reports/{id}' },
    inputSchema: objectSchema({ id: STRING_SCHEMA }, ['id']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'knowledge.jobs.list',
    title: 'List Knowledge Jobs',
    description: 'Return built-in structured knowledge maintenance jobs.',
    category: 'knowledge',
    scopes: ['read:knowledge'],
    http: { method: 'GET', path: '/api/knowledge/jobs' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: listOutputSchema('jobs'),
  }),
  methodDescriptor({
    id: 'knowledge.job.get',
    title: 'Get Knowledge Job',
    description: 'Return a single knowledge job definition.',
    category: 'knowledge',
    scopes: ['read:knowledge'],
    http: { method: 'GET', path: '/api/knowledge/jobs/{jobId}' },
    inputSchema: objectSchema({ jobId: STRING_SCHEMA }, ['jobId']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'knowledge.job-runs.list',
    title: 'List Knowledge Job Runs',
    description: 'Return recent knowledge job runs.',
    category: 'knowledge',
    scopes: ['read:knowledge'],
    http: { method: 'GET', path: '/api/knowledge/job-runs' },
    inputSchema: objectSchema({ limit: NUMBER_SCHEMA, jobId: STRING_SCHEMA }),
    outputSchema: listOutputSchema('runs'),
  }),
  methodDescriptor({
    id: 'knowledge.schedules.list',
    title: 'List Knowledge Schedules',
    description: 'Return managed schedules for background knowledge maintenance jobs.',
    category: 'knowledge',
    scopes: ['read:knowledge'],
    http: { method: 'GET', path: '/api/knowledge/schedules' },
    inputSchema: objectSchema({ limit: NUMBER_SCHEMA }),
    outputSchema: listOutputSchema('schedules'),
  }),
  methodDescriptor({
    id: 'knowledge.schedule.get',
    title: 'Get Knowledge Schedule',
    description: 'Return a single managed knowledge schedule.',
    category: 'knowledge',
    scopes: ['read:knowledge'],
    http: { method: 'GET', path: '/api/knowledge/schedules/{id}' },
    inputSchema: objectSchema({ id: STRING_SCHEMA }, ['id']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'knowledge.schedule.save',
    title: 'Save Knowledge Schedule',
    description: 'Create or update a managed schedule for a knowledge maintenance job.',
    category: 'knowledge',
    scopes: ['write:knowledge'],
    access: 'admin',
    http: { method: 'POST', path: '/api/knowledge/schedules' },
    inputSchema: bodyEnvelopeSchema({ jobId: STRING_SCHEMA, label: STRING_SCHEMA, schedule: GENERIC_OBJECT_SCHEMA }, ['jobId', 'schedule']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'knowledge.schedule.delete',
    title: 'Delete Knowledge Schedule',
    description: 'Delete a managed knowledge schedule.',
    category: 'knowledge',
    scopes: ['write:knowledge'],
    access: 'admin',
    http: { method: 'DELETE', path: '/api/knowledge/schedules/{id}' },
    inputSchema: objectSchema({ id: STRING_SCHEMA }, ['id']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'knowledge.schedule.enable',
    title: 'Set Knowledge Schedule Enabled',
    description: 'Enable or disable a managed knowledge schedule.',
    category: 'knowledge',
    scopes: ['write:knowledge'],
    access: 'admin',
    http: { method: 'POST', path: '/api/knowledge/schedules/{id}/enabled' },
    inputSchema: bodyEnvelopeSchema({ enabled: BOOLEAN_SCHEMA }, ['enabled']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'knowledge.job.run',
    title: 'Run Knowledge Job',
    description: 'Queue or run a structured knowledge maintenance job.',
    category: 'knowledge',
    scopes: ['write:knowledge'],
    access: 'admin',
    http: { method: 'POST', path: '/api/knowledge/jobs/{jobId}/run' },
    events: [runtimeEventId('knowledge')],
    inputSchema: bodyEnvelopeSchema({}),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'knowledge.lint',
    title: 'Lint Structured Knowledge',
    description: 'Run deterministic knowledge lint checks and return the current issues.',
    category: 'knowledge',
    scopes: ['write:knowledge'],
    access: 'admin',
    http: { method: 'POST', path: '/api/knowledge/lint' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'knowledge.reindex',
    title: 'Reindex Structured Knowledge',
    description: 'Rebuild derived knowledge relations and mirror reviewed memory into the structured knowledge store.',
    category: 'knowledge',
    scopes: ['write:knowledge'],
    access: 'admin',
    http: { method: 'POST', path: '/api/knowledge/reindex' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'knowledge.projections.list',
    title: 'List Knowledge Projections',
    description: 'Return renderable markdown/wiki projection targets for the knowledge domain.',
    category: 'knowledge',
    scopes: ['read:knowledge'],
    http: { method: 'GET', path: '/api/knowledge/projections' },
    inputSchema: objectSchema({ limit: NUMBER_SCHEMA }),
    outputSchema: listOutputSchema('targets'),
  }),
  methodDescriptor({
    id: 'knowledge.projection.render',
    title: 'Render Knowledge Projection',
    description: 'Render a markdown/wiki projection from the canonical structured knowledge store.',
    category: 'knowledge',
    scopes: ['read:knowledge'],
    http: { method: 'POST', path: '/api/knowledge/projections/render' },
    inputSchema: bodyEnvelopeSchema({ kind: STRING_SCHEMA }, ['kind']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'knowledge.projection.materialize',
    title: 'Materialize Knowledge Projection',
    description: 'Render and persist a markdown/wiki projection as a derived artifact.',
    category: 'knowledge',
    scopes: ['write:knowledge'],
    access: 'admin',
    http: { method: 'POST', path: '/api/knowledge/projections/materialize' },
    inputSchema: bodyEnvelopeSchema({ kind: STRING_SCHEMA }, ['kind']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'knowledge.graphql.schema',
    title: 'Knowledge GraphQL Schema',
    description: 'Return the SDL for the dedicated knowledge GraphQL endpoint.',
    category: 'knowledge',
    scopes: ['read:knowledge'],
    http: { method: 'GET', path: '/api/knowledge/graphql/schema' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'knowledge.graphql.execute',
    title: 'Execute Knowledge GraphQL',
    description: 'Execute a GraphQL query or mutation against the dedicated knowledge domain endpoint.',
    category: 'knowledge',
    scopes: ['read:knowledge'],
    http: { method: 'POST', path: '/api/knowledge/graphql' },
    inputSchema: bodyEnvelopeSchema({ query: STRING_SCHEMA }, ['query']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'voice.status',
    title: 'Voice Status',
    description: 'Return configured voice provider posture and capabilities.',
    category: 'voice',
    scopes: ['read:voice'],
    http: { method: 'GET', path: '/api/voice' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'voice.providers.list',
    title: 'List Voice Providers',
    description: 'Return registered voice providers.',
    category: 'voice',
    scopes: ['read:voice'],
    http: { method: 'GET', path: '/api/voice/providers' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: listOutputSchema('providers'),
  }),
  methodDescriptor({
    id: 'voice.voices.list',
    title: 'List Voices',
    description: 'Return registered voices for a voice provider.',
    category: 'voice',
    scopes: ['read:voice'],
    http: { method: 'GET', path: '/api/voice/voices' },
    inputSchema: objectSchema({ providerId: STRING_SCHEMA }),
    outputSchema: listOutputSchema('voices'),
  }),
  methodDescriptor({
    id: 'voice.tts',
    title: 'Run Text To Speech',
    description: 'Synthesize audio through a registered voice provider.',
    category: 'voice',
    scopes: ['write:voice'],
    http: { method: 'POST', path: '/api/voice/tts' },
    inputSchema: bodyEnvelopeSchema({ text: STRING_SCHEMA }, ['text']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'voice.stt',
    title: 'Run Speech To Text',
    description: 'Transcribe an audio artifact through a registered voice provider.',
    category: 'voice',
    scopes: ['write:voice'],
    http: { method: 'POST', path: '/api/voice/stt' },
    inputSchema: bodyEnvelopeSchema({ audio: GENERIC_OBJECT_SCHEMA }, ['audio']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'voice.realtime.session',
    title: 'Open Voice Realtime Session',
    description: 'Open a realtime voice session through a registered voice provider.',
    category: 'voice',
    scopes: ['write:voice'],
    http: { method: 'POST', path: '/api/voice/realtime/session' },
    inputSchema: GENERIC_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'web_search.providers.list',
    title: 'List Web Search Providers',
    description: 'Return registered web search provider capabilities.',
    category: 'web-search',
    scopes: ['read:web-search'],
    http: { method: 'GET', path: '/api/web-search/providers' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: listOutputSchema('providers'),
  }),
  methodDescriptor({
    id: 'web_search.query',
    title: 'Run Web Search',
    description: 'Execute a provider-backed web search and return normalized ranked results.',
    category: 'web-search',
    scopes: ['write:web-search'],
    http: { method: 'POST', path: '/api/web-search/query' },
    inputSchema: bodyEnvelopeSchema({ query: STRING_SCHEMA }, ['query']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'artifacts.list',
    title: 'List Artifacts',
    description: 'Return stored artifact metadata for files and attachments.',
    category: 'artifacts',
    scopes: ['read:artifacts'],
    http: { method: 'GET', path: '/api/artifacts' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: listOutputSchema('artifacts'),
  }),
  methodDescriptor({
    id: 'artifacts.create',
    title: 'Create Artifact',
    description: 'Store a file or attachment artifact for later delivery or analysis.',
    category: 'artifacts',
    scopes: ['write:artifacts'],
    http: { method: 'POST', path: '/api/artifacts' },
    inputSchema: GENERIC_OBJECT_SCHEMA,
    outputSchema: entityOutputSchema('artifact'),
  }),
  methodDescriptor({
    id: 'artifacts.get',
    title: 'Get Artifact',
    description: 'Return metadata for a stored artifact.',
    category: 'artifacts',
    scopes: ['read:artifacts'],
    http: { method: 'GET', path: '/api/artifacts/{artifactId}' },
    inputSchema: objectSchema({ artifactId: STRING_SCHEMA }, ['artifactId']),
    outputSchema: entityOutputSchema('artifact'),
  }),
  methodDescriptor({
    id: 'artifacts.content.get',
    title: 'Get Artifact Content',
    description: 'Return the raw content bytes for a stored artifact.',
    category: 'artifacts',
    scopes: ['read:artifacts'],
    transport: ['http'],
    http: { method: 'GET', path: '/api/artifacts/{artifactId}/content' },
    inputSchema: objectSchema({
      artifactId: STRING_SCHEMA,
      download: STRING_SCHEMA,
    }, ['artifactId']),
    outputSchema: objectSchema({
      contentType: STRING_SCHEMA,
      contentLength: NUMBER_SCHEMA,
    }, ['contentType', 'contentLength']),
    invokable: false,
    metadata: { responseKind: 'binary' },
  }),
  methodDescriptor({
    id: 'media.providers.list',
    title: 'List Media Providers',
    description: 'Return registered media provider capabilities.',
    category: 'media',
    scopes: ['read:media'],
    http: { method: 'GET', path: '/api/media/providers' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: listOutputSchema('providers'),
  }),
  methodDescriptor({
    id: 'media.analyze',
    title: 'Analyze Media Artifact',
    description: 'Analyze an artifact through a registered media provider.',
    category: 'media',
    scopes: ['write:media'],
    http: { method: 'POST', path: '/api/media/analyze' },
    inputSchema: GENERIC_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'media.transform',
    title: 'Transform Media Artifact',
    description: 'Transform an artifact through a registered media provider.',
    category: 'media',
    scopes: ['write:media'],
    http: { method: 'POST', path: '/api/media/transform' },
    inputSchema: GENERIC_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'media.generate',
    title: 'Generate Media Artifact',
    description: 'Generate a media artifact through a registered media provider.',
    category: 'media',
    scopes: ['write:media'],
    http: { method: 'POST', path: '/api/media/generate' },
    inputSchema: GENERIC_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'multimodal.status',
    title: 'Multimodal Status',
    description: 'Return the unified multimodal runtime status across image, audio, video, and document analysis.',
    category: 'media',
    scopes: ['read:media'],
    http: { method: 'GET', path: '/api/multimodal' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'multimodal.providers.list',
    title: 'List Multimodal Providers',
    description: 'Return the normalized multimodal provider catalog spanning media understanding, speech-to-text, and extractors.',
    category: 'media',
    scopes: ['read:media'],
    http: { method: 'GET', path: '/api/multimodal/providers' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: listOutputSchema('providers'),
  }),
  methodDescriptor({
    id: 'multimodal.analyze',
    title: 'Run Multimodal Analysis',
    description: 'Analyze an image, audio file, video artifact, or document through the unified multimodal service.',
    category: 'media',
    scopes: ['write:media'],
    http: { method: 'POST', path: '/api/multimodal/analyze' },
    inputSchema: GENERIC_OBJECT_SCHEMA,
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'multimodal.packet',
    title: 'Build Multimodal Packet',
    description: 'Build a token-efficient packet from an existing multimodal analysis result.',
    category: 'media',
    scopes: ['read:media'],
    http: { method: 'POST', path: '/api/multimodal/packet' },
    inputSchema: bodyEnvelopeSchema({ analysis: GENERIC_OBJECT_SCHEMA }, ['analysis']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
  methodDescriptor({
    id: 'multimodal.writeback',
    title: 'Write Back Multimodal Analysis',
    description: 'Persist a multimodal analysis result as an artifact and ingest it into the structured knowledge store.',
    category: 'media',
    scopes: ['write:media', 'write:knowledge'],
    access: 'admin',
    http: { method: 'POST', path: '/api/multimodal/writeback' },
    inputSchema: bodyEnvelopeSchema({ analysis: GENERIC_OBJECT_SCHEMA }, ['analysis']),
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
];
