import type { GatewayMethodDescriptor } from './method-catalog-shared.ts';
import {
  BOOLEAN_SCHEMA,
  EMPTY_OBJECT_SCHEMA,
  NUMBER_SCHEMA,
  STRING_SCHEMA,
  arraySchema,
  actionResultOutputSchema,
  bodyEnvelopeSchema,
  entityOutputSchema,
  listOutputSchema,
  methodDescriptor,
  objectSchema,
  runtimeEventId,
  METHOD_DESCRIPTOR_SCHEMA,
  EVENT_DESCRIPTOR_SCHEMA,
} from './method-catalog-shared.ts';
import {
  APPROVAL_ACTION_INPUT_SCHEMA,
  APPROVAL_ACTION_OUTPUT_SCHEMA,
  APPROVAL_SNAPSHOT_SCHEMA,
  CONTROL_PLANE_CLIENT_DESCRIPTOR_SCHEMA,
  CONTROL_PLANE_SURFACE_MESSAGE_SCHEMA,
  CONTROL_PLANE_SNAPSHOT_SCHEMA,
  REVIEW_SNAPSHOT_SCHEMA,
  SESSION_BROKER_SNAPSHOT_SCHEMA,
  SESSION_SNAPSHOT_SCHEMA,
  SHARED_SESSION_CREATE_OUTPUT_SCHEMA,
  SHARED_SESSION_MESSAGE_CREATE_OUTPUT_SCHEMA,
  SHARED_SESSION_RECORD_SCHEMA,
  SHARED_SESSION_WITH_MESSAGES_SCHEMA,
  TASK_ACTION_OUTPUT_SCHEMA,
  TASK_CREATE_INPUT_SCHEMA,
  TASK_CREATE_OUTPUT_SCHEMA,
  TASK_OUTPUT_SCHEMA,
  TASK_SNAPSHOT_SCHEMA,
  TASK_STATUS_OUTPUT_SCHEMA,
} from './operator-contract-schemas.ts';
import { OPERATOR_CONTRACT_SCHEMA } from './operator-contract.ts';

export const builtinGatewayControlCoreMethodDescriptors: readonly GatewayMethodDescriptor[] = [
  methodDescriptor({
    id: 'control.auth.login',
    title: 'Login',
    description: 'Authenticate a local control-plane user and create a session token.',
    category: 'control-plane',
    access: 'public',
    transport: ['http'],
    scopes: [],
    http: { method: 'POST', path: '/login' },
    inputSchema: bodyEnvelopeSchema({
      username: STRING_SCHEMA,
      password: STRING_SCHEMA,
    }, ['username', 'password']),
    outputSchema: objectSchema({
      authenticated: BOOLEAN_SCHEMA,
      token: STRING_SCHEMA,
      username: STRING_SCHEMA,
      expiresAt: NUMBER_SCHEMA,
    }, ['authenticated', 'token', 'username', 'expiresAt']),
    invokable: false,
  }),
  methodDescriptor({
    id: 'control.status',
    title: 'Daemon Status',
    description: 'Return daemon status and version.',
    category: 'control-plane',
    scopes: ['read:control-plane'],
    http: { method: 'GET', path: '/status' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: objectSchema({
      status: STRING_SCHEMA,
      version: STRING_SCHEMA,
    }, ['status', 'version']),
  }),
  methodDescriptor({
    id: 'control.snapshot',
    title: 'Control-Plane Snapshot',
    description: 'Return the current control-plane gateway snapshot.',
    category: 'control-plane',
    scopes: ['read:control-plane'],
    http: { method: 'GET', path: '/api/control-plane' },
    events: [runtimeEventId('control-plane')],
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: CONTROL_PLANE_SNAPSHOT_SCHEMA,
  }),
  methodDescriptor({
    id: 'control.contract',
    title: 'Operator Contract',
    description: 'Return the operator-facing control-plane contract manifest, including auth, transport, method, and event metadata.',
    category: 'control-plane',
    scopes: ['read:control-plane'],
    http: { method: 'GET', path: '/api/control-plane/contract' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: entityOutputSchema('contract', OPERATOR_CONTRACT_SCHEMA),
  }),
  methodDescriptor({
    id: 'control.web',
    title: 'Control-Plane Web Shell',
    description: 'Return the built-in control-plane HTML shell for external clients.',
    category: 'control-plane',
    scopes: ['read:control-plane'],
    transport: ['http'],
    http: { method: 'GET', path: '/api/control-plane/web' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: objectSchema({ html: STRING_SCHEMA }, ['html']),
    invokable: false,
    metadata: { responseKind: 'html' },
  }),
  methodDescriptor({
    id: 'control.messages.list',
    title: 'List Control-Plane Messages',
    description: 'Return recent surface messages published through the control plane.',
    category: 'control-plane',
    scopes: ['read:control-plane'],
    http: { method: 'GET', path: '/api/control-plane/messages' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: listOutputSchema('messages', CONTROL_PLANE_SURFACE_MESSAGE_SCHEMA),
  }),
  methodDescriptor({
    id: 'control.clients.list',
    title: 'List Control-Plane Clients',
    description: 'Return authenticated and recently connected control-plane clients.',
    category: 'control-plane',
    scopes: ['read:control-plane'],
    http: { method: 'GET', path: '/api/control-plane/clients' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: listOutputSchema('clients', CONTROL_PLANE_CLIENT_DESCRIPTOR_SCHEMA),
  }),
  methodDescriptor({
    id: 'control.methods.list',
    title: 'List Gateway Methods',
    description: 'Return the gateway method catalog.',
    category: 'control-plane',
    scopes: ['read:control-plane'],
    http: { method: 'GET', path: '/api/control-plane/methods' },
    inputSchema: objectSchema({
      category: STRING_SCHEMA,
      source: STRING_SCHEMA,
    }),
    outputSchema: listOutputSchema('methods', METHOD_DESCRIPTOR_SCHEMA),
  }),
  methodDescriptor({
    id: 'control.methods.get',
    title: 'Get Gateway Method',
    description: 'Return a single gateway method descriptor.',
    category: 'control-plane',
    scopes: ['read:control-plane'],
    http: { method: 'GET', path: '/api/control-plane/methods/{methodId}' },
    inputSchema: objectSchema({
      methodId: STRING_SCHEMA,
    }, ['methodId']),
    outputSchema: entityOutputSchema('method', METHOD_DESCRIPTOR_SCHEMA),
  }),
  methodDescriptor({
    id: 'control.events.catalog',
    title: 'List Gateway Events',
    description: 'Return the event catalog for SSE and WebSocket control-plane subscriptions.',
    category: 'control-plane',
    scopes: ['read:control-plane', 'read:events'],
    http: { method: 'GET', path: '/api/control-plane/events/catalog' },
    inputSchema: objectSchema({
      category: STRING_SCHEMA,
      domain: STRING_SCHEMA,
    }),
    outputSchema: listOutputSchema('events', EVENT_DESCRIPTOR_SCHEMA),
  }),
  methodDescriptor({
    id: 'control.events.stream',
    title: 'Open Control-Plane Event Stream',
    description: 'Open the SSE control-plane event stream.',
    category: 'control-plane',
    scopes: ['read:events'],
    transport: ['http'],
    http: { method: 'GET', path: '/api/control-plane/events' },
    inputSchema: objectSchema({
      domains: STRING_SCHEMA,
    }),
    outputSchema: objectSchema({
      contentType: STRING_SCHEMA,
      mode: STRING_SCHEMA,
    }, ['contentType', 'mode']),
    invokable: false,
    metadata: { responseKind: 'sse', stream: true },
  }),
  methodDescriptor({
    id: 'review.snapshot',
    title: 'Review Snapshot',
    description: 'Return the integration review snapshot used by external helpers.',
    category: 'review',
    scopes: ['read:automation'],
    http: { method: 'GET', path: '/api/review' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: REVIEW_SNAPSHOT_SCHEMA,
  }),
  methodDescriptor({
    id: 'sessions.integration.snapshot',
    title: 'Legacy Session Snapshot',
    description: 'Return the legacy integration session snapshot.',
    category: 'sessions',
    scopes: ['read:sessions'],
    http: { method: 'GET', path: '/api/session' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: SESSION_SNAPSHOT_SCHEMA,
  }),
  methodDescriptor({
    id: 'sessions.list',
    title: 'List Shared Sessions',
    description: 'Return shared-session integration state.',
    category: 'sessions',
    scopes: ['read:sessions'],
    http: { method: 'GET', path: '/api/sessions' },
    events: [runtimeEventId('session')],
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: SESSION_BROKER_SNAPSHOT_SCHEMA,
  }),
  methodDescriptor({
    id: 'sessions.create',
    title: 'Create Shared Session',
    description: 'Create a shared session for a surface, route, or web client.',
    category: 'sessions',
    scopes: ['write:sessions'],
    http: { method: 'POST', path: '/api/sessions' },
    inputSchema: bodyEnvelopeSchema({
      title: STRING_SCHEMA,
      surfaceKind: STRING_SCHEMA,
      surfaceId: STRING_SCHEMA,
    }),
    outputSchema: SHARED_SESSION_CREATE_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'sessions.get',
    title: 'Get Shared Session',
    description: 'Return metadata for a shared session.',
    category: 'sessions',
    scopes: ['read:sessions'],
    http: { method: 'GET', path: '/api/sessions/{sessionId}' },
    inputSchema: objectSchema({ sessionId: STRING_SCHEMA }, ['sessionId']),
    outputSchema: SHARED_SESSION_WITH_MESSAGES_SCHEMA,
  }),
  methodDescriptor({
    id: 'sessions.close',
    title: 'Close Shared Session',
    description: 'Mark a shared session as closed.',
    category: 'sessions',
    scopes: ['write:sessions'],
    http: { method: 'POST', path: '/api/sessions/{sessionId}/close' },
    inputSchema: objectSchema({ sessionId: STRING_SCHEMA }, ['sessionId']),
    outputSchema: actionResultOutputSchema('session', SHARED_SESSION_RECORD_SCHEMA),
  }),
  methodDescriptor({
    id: 'sessions.reopen',
    title: 'Reopen Shared Session',
    description: 'Reopen a previously closed shared session.',
    category: 'sessions',
    scopes: ['write:sessions'],
    http: { method: 'POST', path: '/api/sessions/{sessionId}/reopen' },
    inputSchema: objectSchema({ sessionId: STRING_SCHEMA }, ['sessionId']),
    outputSchema: actionResultOutputSchema('session', SHARED_SESSION_RECORD_SCHEMA),
  }),
  methodDescriptor({
    id: 'sessions.messages.list',
    title: 'List Shared Session Messages',
    description: 'Return message history for a shared session.',
    category: 'sessions',
    scopes: ['read:sessions'],
    http: { method: 'GET', path: '/api/sessions/{sessionId}/messages' },
    inputSchema: objectSchema({
      sessionId: STRING_SCHEMA,
      limit: NUMBER_SCHEMA,
      before: STRING_SCHEMA,
    }, ['sessionId']),
    outputSchema: SHARED_SESSION_WITH_MESSAGES_SCHEMA,
  }),
  methodDescriptor({
    id: 'sessions.messages.create',
    title: 'Post Shared Session Message',
    description: 'Append a user message to a shared session and queue assistant work.',
    category: 'sessions',
    scopes: ['write:sessions'],
    http: { method: 'POST', path: '/api/sessions/{sessionId}/messages' },
    inputSchema: bodyEnvelopeSchema({
      body: STRING_SCHEMA,
      surfaceKind: STRING_SCHEMA,
      surfaceId: STRING_SCHEMA,
    }, ['body']),
    outputSchema: SHARED_SESSION_MESSAGE_CREATE_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'tasks.list',
    title: 'List Runtime Tasks',
    description: 'Return the integration snapshot for runtime tasks.',
    category: 'tasks',
    scopes: ['read:tasks'],
    http: { method: 'GET', path: '/api/tasks' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: TASK_SNAPSHOT_SCHEMA,
  }),
  methodDescriptor({
    id: 'tasks.create',
    title: 'Create Task',
    description: 'Submit a task to the daemon or a shared session.',
    category: 'tasks',
    scopes: ['write:tasks'],
    http: { method: 'POST', path: '/task' },
    events: [runtimeEventId('tasks')],
    inputSchema: TASK_CREATE_INPUT_SCHEMA,
    outputSchema: TASK_CREATE_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'tasks.get',
    title: 'Get Runtime Task',
    description: 'Return a single runtime task record.',
    category: 'tasks',
    scopes: ['read:tasks'],
    http: { method: 'GET', path: '/api/tasks/{taskId}' },
    inputSchema: objectSchema({ taskId: STRING_SCHEMA }, ['taskId']),
    outputSchema: TASK_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'tasks.cancel',
    title: 'Cancel Runtime Task',
    description: 'Cancel an in-flight runtime task.',
    category: 'tasks',
    scopes: ['write:tasks'],
    http: { method: 'POST', path: '/api/tasks/{taskId}/cancel' },
    inputSchema: objectSchema({ taskId: STRING_SCHEMA }, ['taskId']),
    outputSchema: TASK_ACTION_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'tasks.retry',
    title: 'Retry Runtime Task',
    description: 'Retry a runtime task through the task action endpoint.',
    category: 'tasks',
    scopes: ['write:tasks'],
    http: { method: 'POST', path: '/api/tasks/{taskId}/retry' },
    inputSchema: objectSchema({ taskId: STRING_SCHEMA }, ['taskId']),
    outputSchema: TASK_ACTION_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'tasks.status',
    title: 'Get Task Status',
    description: 'Return lightweight runtime task status by agent id.',
    category: 'tasks',
    scopes: ['read:tasks'],
    http: { method: 'GET', path: '/task/{agentId}' },
    inputSchema: objectSchema({ agentId: STRING_SCHEMA }, ['agentId']),
    outputSchema: TASK_STATUS_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'approvals.list',
    title: 'List Approvals',
    description: 'Return pending and historical approval records.',
    category: 'approvals',
    scopes: ['read:approvals'],
    http: { method: 'GET', path: '/api/approvals' },
    inputSchema: EMPTY_OBJECT_SCHEMA,
    outputSchema: APPROVAL_SNAPSHOT_SCHEMA,
  }),
  methodDescriptor({
    id: 'approvals.claim',
    title: 'Claim Approval',
    description: 'Claim a pending approval for operator handling.',
    category: 'approvals',
    scopes: ['write:approvals'],
    http: { method: 'POST', path: '/api/approvals/{approvalId}/claim' },
    inputSchema: objectSchema({ approvalId: STRING_SCHEMA }, ['approvalId']),
    outputSchema: APPROVAL_ACTION_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'approvals.approve',
    title: 'Approve Approval',
    description: 'Approve a pending approval.',
    category: 'approvals',
    scopes: ['write:approvals'],
    http: { method: 'POST', path: '/api/approvals/{approvalId}/approve' },
    inputSchema: APPROVAL_ACTION_INPUT_SCHEMA,
    outputSchema: APPROVAL_ACTION_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'approvals.deny',
    title: 'Deny Approval',
    description: 'Deny a pending approval.',
    category: 'approvals',
    scopes: ['write:approvals'],
    http: { method: 'POST', path: '/api/approvals/{approvalId}/deny' },
    inputSchema: APPROVAL_ACTION_INPUT_SCHEMA,
    outputSchema: APPROVAL_ACTION_OUTPUT_SCHEMA,
  }),
  methodDescriptor({
    id: 'approvals.cancel',
    title: 'Cancel Approval',
    description: 'Cancel a pending approval.',
    category: 'approvals',
    scopes: ['write:approvals'],
    http: { method: 'POST', path: '/api/approvals/{approvalId}/cancel' },
    inputSchema: APPROVAL_ACTION_INPUT_SCHEMA,
    outputSchema: APPROVAL_ACTION_OUTPUT_SCHEMA,
  }),
];
