import type { GatewayEventDescriptor } from './method-catalog-shared.ts';
import { GENERIC_OBJECT_SCHEMA,STRING_SCHEMA,NUMBER_SCHEMA,arraySchema,objectSchema,eventDescriptor,runtimeDomainEvent } from './method-catalog-shared.ts';

export const builtinGatewayEventDescriptors: readonly GatewayEventDescriptor[] = [
  runtimeDomainEvent('session', 'Shared-session lifecycle, participant, and message events.'),
  runtimeDomainEvent('turn', 'Turn submission and completion events.'),
  runtimeDomainEvent('providers', 'Provider health, selection, and routing events.'),
  runtimeDomainEvent('tools', 'Tool start, result, and failure events.'),
  runtimeDomainEvent('tasks', 'Runtime task lifecycle and status events.'),
  runtimeDomainEvent('agents', 'Agent lifecycle, planning, and completion events.'),
  runtimeDomainEvent('workflows', 'Workflow orchestration events.'),
  runtimeDomainEvent('orchestration', 'Higher-level orchestration and planner coordination events.'),
  runtimeDomainEvent('communication', 'Agent communication and policy events.'),
  runtimeDomainEvent('planner', 'Planner updates and plan mutation events.'),
  runtimeDomainEvent('permissions', 'Approval and permission prompt events.'),
  runtimeDomainEvent('plugins', 'Plugin registration and lifecycle events.'),
  runtimeDomainEvent('mcp', 'MCP server, tool, and connection events.'),
  runtimeDomainEvent('transport', 'Transport connect, disconnect, and lifecycle events.'),
  runtimeDomainEvent('compaction', 'Context compaction and summary events.'),
  runtimeDomainEvent('ui', 'UI-focused state and operational events.'),
  runtimeDomainEvent('ops', 'Operational diagnostics and control events.'),
  runtimeDomainEvent('forensics', 'Forensics and incident trail events.'),
  runtimeDomainEvent('security', 'Security posture and policy events.'),
  runtimeDomainEvent('automation', 'Automation job, schedule, and run events.'),
  runtimeDomainEvent('routes', 'Route binding and surface-link events.'),
  runtimeDomainEvent('control-plane', 'Control-plane client, auth, and subscription events.'),
  runtimeDomainEvent('deliveries', 'Delivery queue and outcome events.'),
  runtimeDomainEvent('watchers', 'Watcher state and heartbeat events.'),
  runtimeDomainEvent('surfaces', 'Surface registration and health events.'),
  runtimeDomainEvent('knowledge', 'Knowledge ingest, extraction, projection, packet, and job events.'),
  eventDescriptor({
    id: 'control.ready',
    title: 'Ready Handshake',
    description: 'Initial SSE/WebSocket handshake event emitted after a control-plane subscription is opened.',
    category: 'transport',
    transport: ['sse', 'ws'],
    scopes: ['read:events'],
    wireEvents: ['ready'],
    outputSchema: objectSchema({
      clientId: STRING_SCHEMA,
      domains: arraySchema(STRING_SCHEMA),
      transport: STRING_SCHEMA,
    }, ['clientId', 'domains'], { additionalProperties: true }),
  }),
  eventDescriptor({
    id: 'control.heartbeat',
    title: 'Heartbeat',
    description: 'Keepalive event emitted by the SSE control-plane transport.',
    category: 'transport',
    transport: ['sse', 'ws'],
    scopes: ['read:events'],
    wireEvents: ['heartbeat'],
    outputSchema: objectSchema({
      clientId: STRING_SCHEMA,
      ts: NUMBER_SCHEMA,
    }, ['clientId', 'ts'], { additionalProperties: false }),
  }),
  eventDescriptor({
    id: 'control.surface_message',
    title: 'Surface Message',
    description: 'Out-of-band control-plane surface messages for operators and connected clients.',
    category: 'transport',
    transport: ['sse', 'ws'],
    scopes: ['read:events'],
    wireEvents: ['surface-message'],
    outputSchema: GENERIC_OBJECT_SCHEMA,
  }),
];
