import type { ExternalSurfaceSpec } from './onboarding-wizard-external-surfaces.ts';

export const WEBHOOK_SURFACE_SPEC: ExternalSurfaceSpec = {
  id: 'webhook',
  enabledFieldId: 'external-services.webhook',
  enabledConfigKey: 'surfaces.webhook.enabled',
  label: 'Outbound webhook surface',
  hint: 'Enable outbound webhook delivery targets.',
  defaultEnabled: (snapshot) => snapshot?.config.surfaces.webhook.enabled ?? false,
  fields: [
    {
      id: 'external-services.webhook.default-target',
      configKey: 'surfaces.webhook.defaultTarget',
      kind: 'text',
      label: 'Default webhook target',
      hint: 'Fallback URL used for outbound webhook deliveries.',
      placeholder: 'https://example.com/goodvibes',
      defaultValue: (snapshot) => snapshot?.config.surfaces.webhook.defaultTarget ?? '',
    },
    {
      id: 'external-services.webhook.secret',
      configKey: 'surfaces.webhook.secret',
      kind: 'masked',
      label: 'Webhook signing secret',
      hint: 'Secret used to sign outbound webhook payloads.',
      placeholder: 'secret',
      defaultValue: (snapshot) => snapshot?.config.surfaces.webhook.secret ?? '',
    },
    {
      id: 'external-services.webhook.timeout-ms',
      configKey: 'surfaces.webhook.timeoutMs',
      kind: 'text',
      valueType: 'number',
      label: 'Webhook timeout ms',
      hint: 'Request timeout for outbound webhook deliveries.',
      placeholder: '10000',
      defaultNumber: 10000,
      min: 1000,
      max: 60000,
      defaultValue: (snapshot) => String(snapshot?.config.surfaces.webhook.timeoutMs ?? 10000),
    },
  ],
};

export const HOME_ASSISTANT_SURFACE_SPEC: ExternalSurfaceSpec = {
  id: 'homeassistant',
  enabledFieldId: 'external-services.homeassistant',
  enabledConfigKey: 'surfaces.homeassistant.enabled',
  label: 'Home Assistant surface',
  hint: 'Enable the Home Assistant companion surface, daemon callbacks, and event delivery.',
  defaultEnabled: (snapshot) => snapshot?.config.surfaces.homeassistant.enabled ?? false,
  fields: [
    {
      id: 'external-services.homeassistant.instance-url',
      configKey: 'surfaces.homeassistant.instanceUrl',
      kind: 'text',
      label: 'Home Assistant URL',
      hint: 'Base URL of the Home Assistant instance.',
      placeholder: 'http://homeassistant.local:8123',
      defaultValue: (snapshot) => snapshot?.config.surfaces.homeassistant.instanceUrl ?? '',
    },
    {
      id: 'external-services.homeassistant.access-token',
      configKey: 'surfaces.homeassistant.accessToken',
      kind: 'masked',
      label: 'Home Assistant access token',
      hint: 'Long-lived Home Assistant access token or goodvibes:// secret reference.',
      placeholder: 'long-lived access token',
      defaultValue: (snapshot) => snapshot?.config.surfaces.homeassistant.accessToken ?? '',
    },
    {
      id: 'external-services.homeassistant.webhook-secret',
      configKey: 'surfaces.homeassistant.webhookSecret',
      kind: 'masked',
      label: 'Home Assistant webhook secret',
      hint: 'Shared secret used to verify inbound Home Assistant callbacks.',
      placeholder: 'webhook secret',
      defaultValue: (snapshot) => snapshot?.config.surfaces.homeassistant.webhookSecret ?? '',
    },
    {
      id: 'external-services.homeassistant.default-conversation-id',
      configKey: 'surfaces.homeassistant.defaultConversationId',
      kind: 'text',
      label: 'Default conversation ID',
      hint: 'Default Home Assistant conversation id used for route binding.',
      placeholder: 'goodvibes',
      defaultValue: (snapshot) => snapshot?.config.surfaces.homeassistant.defaultConversationId ?? 'goodvibes',
    },
    {
      id: 'external-services.homeassistant.remote-session-ttl-ms',
      configKey: 'surfaces.homeassistant.remoteSessionTtlMs',
      kind: 'text',
      valueType: 'number',
      label: 'Remote session idle TTL ms',
      hint: 'How long an idle Home Assistant remote conversation session remains open before the daemon closes it.',
      placeholder: '1200000',
      defaultNumber: 1_200_000,
      min: 60_000,
      max: 86_400_000,
      defaultValue: (snapshot) => String(snapshot?.config.surfaces.homeassistant.remoteSessionTtlMs ?? 1_200_000),
    },
    {
      id: 'external-services.homeassistant.device-id',
      configKey: 'surfaces.homeassistant.deviceId',
      kind: 'text',
      label: 'Home Assistant device ID',
      hint: 'Stable device identifier exposed by the GoodVibes daemon.',
      placeholder: 'goodvibes-daemon',
      defaultValue: (snapshot) => snapshot?.config.surfaces.homeassistant.deviceId ?? 'goodvibes-daemon',
    },
    {
      id: 'external-services.homeassistant.device-name',
      configKey: 'surfaces.homeassistant.deviceName',
      kind: 'text',
      label: 'Home Assistant device name',
      hint: 'Display name for the GoodVibes daemon device in Home Assistant.',
      placeholder: 'GoodVibes Daemon',
      defaultValue: (snapshot) => snapshot?.config.surfaces.homeassistant.deviceName ?? 'GoodVibes Daemon',
    },
    {
      id: 'external-services.homeassistant.event-type',
      configKey: 'surfaces.homeassistant.eventType',
      kind: 'text',
      label: 'Home Assistant event type',
      hint: 'Event type used for daemon-to-Home Assistant deliveries.',
      placeholder: 'goodvibes_message',
      defaultValue: (snapshot) => snapshot?.config.surfaces.homeassistant.eventType ?? 'goodvibes_message',
    },
  ],
};
