/**
 * context-compaction.ts
 *
 * Auto context compaction for goodvibes-tui.
 *
 * Strategy:
 *   1. Preserve the last N messages verbatim (configurable, default: 10)
 *   2. Summarize older user/assistant/tool message pairs into condensed bullet-point form
 *   3. Track compaction events for debugging
 *
 * Note: ProviderMessage does not include 'system' role messages — those are passed
 * separately as systemPrompt and are always preserved unchanged.
 *
 * Public API:
 *   checkAndCompact(opts)               — check usage and compact if threshold exceeded
 *   compactMessages(opts)               — perform compaction, returns new message list
 *   estimateConversationTokens(messages) — rough token count for a message array
 *   shouldAutoCompact(opts)             — check if threshold is exceeded
 *   getCompactionEvents()               — return compaction event log
 *   getLastCompactionEvent()            — return most recent compaction event
 */

import type { ProviderMessage, ContentPart, LLMProvider } from '../providers/interface.ts';
import type { ProviderRegistry } from '../providers/registry.ts';
import { logger } from '../utils/logger.ts';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface CompactionEvent {
  timestamp: number;
  messagesBeforeCompaction: number;
  messagesAfterCompaction: number;
  tokensBeforeEstimate: number;
  tokensAfterEstimate: number;
  modelId: string;
  trigger: 'auto' | 'manual';
}

export interface CompactionOptions {
  /** Provider registry to get the LLM provider from. */
  registry: ProviderRegistry;
  /** Model ID to use for summarization. */
  modelId: string;
  /** Current messages (as sent to the LLM — no system messages). */
  messages: ProviderMessage[];
  /** Number of recent messages to keep verbatim (default: 10). */
  keepRecentMessages?: number;
  /** Whether this was triggered automatically or manually (default: 'manual'). */
  trigger?: 'auto' | 'manual';
}

export interface CompactionResult {
  /** The new compacted message list (no system messages — same format as input). */
  messages: ProviderMessage[];
  /** The summary text generated by the LLM. */
  summary: string;
  /** Token estimates before and after compaction. */
  tokensBeforeEstimate: number;
  tokensAfterEstimate: number;
  /** The compaction event record for tracking. */
  event: CompactionEvent;
}

export interface AutoCompactOptions {
  /** Current input token count from last LLM response. */
  currentTokens: number;
  /** Maximum context window for the current model. */
  contextWindow: number;
  /** Threshold percentage (0-100) at which to trigger compaction (default: 80). */
  threshold: number;
  /** Whether auto-compact is already in progress (prevent re-entry). */
  isCompacting: boolean;
}

// ---------------------------------------------------------------------------
// Compaction event log (in-memory, session-scoped)
// ---------------------------------------------------------------------------

const compactionEvents: CompactionEvent[] = [];

export function getCompactionEvents(): readonly CompactionEvent[] {
  return compactionEvents;
}

export function getLastCompactionEvent(): CompactionEvent | null {
  return compactionEvents.length > 0
    ? compactionEvents[compactionEvents.length - 1]
    : null;
}

// ---------------------------------------------------------------------------
// Token estimation
// ---------------------------------------------------------------------------

/** Rough token estimate: 4 chars ≈ 1 token. Used for threshold checks. */
export function estimateConversationTokens(messages: ProviderMessage[]): number {
  let total = 0;
  for (const msg of messages) {
    if (typeof msg.content === 'string') {
      total += Math.ceil(msg.content.length / 4);
    } else if (Array.isArray(msg.content)) {
      for (const part of msg.content as ContentPart[]) {
        if (part.type === 'text') {
          total += Math.ceil(part.text.length / 4);
        }
      }
    }
  }
  return total;
}

// ---------------------------------------------------------------------------
// Should compact?
// ---------------------------------------------------------------------------

/**
 * Returns true if the context usage exceeds the threshold and compaction
 * has not already been triggered.
 */
export function shouldAutoCompact(opts: AutoCompactOptions): boolean {
  const { currentTokens, contextWindow, threshold, isCompacting } = opts;
  if (isCompacting || contextWindow <= 0) return false;
  const usagePct = (currentTokens / contextWindow) * 100;
  return usagePct >= threshold;
}

// ---------------------------------------------------------------------------
// Core compaction logic
// ---------------------------------------------------------------------------

/**
 * Extract plain text from a ProviderMessage content field.
 */
function extractText(content: string | ContentPart[]): string {
  if (typeof content === 'string') return content;
  return (content as ContentPart[])
    .filter((p): p is { type: 'text'; text: string } => p.type === 'text')
    .map(p => p.text)
    .join('');
}

/**
 * Partition messages into recent (keep verbatim) and older (to be summarized).
 *
 * ProviderMessage has no 'system' role — those are handled separately as systemPrompt.
 */
function partitionMessages(
  messages: ProviderMessage[],
  keepRecent: number,
): {
  recentMessages: ProviderMessage[];
  olderMessages: ProviderMessage[];
} {
  if (messages.length <= keepRecent) {
    return { recentMessages: messages, olderMessages: [] };
  }

  const recentMessages = messages.slice(-keepRecent);
  const olderMessages = messages.slice(0, messages.length - keepRecent);

  return { recentMessages, olderMessages };
}

/**
 * Build a summarization prompt from the older messages.
 */
/** Maximum tokens allowed for the older-messages section of the summarization prompt. */
const MAX_PROMPT_OLDER_TOKENS = 80_000;

function buildSummarizationPrompt(olderMessages: ProviderMessage[]): string {
  // Truncate oldest messages if the total token estimate exceeds the budget.
  let budgetedMessages = olderMessages;
  const totalTokens = estimateConversationTokens(olderMessages);
  if (totalTokens > MAX_PROMPT_OLDER_TOKENS) {
    // Drop from the oldest end until we fit within budget.
    let running = totalTokens;
    let dropIdx = 0;
    for (let i = 0; i < olderMessages.length && running > MAX_PROMPT_OLDER_TOKENS; i++) {
      const msg = olderMessages[i];
      const msgTokens = estimateConversationTokens([msg]);
      running -= msgTokens;
      dropIdx = i + 1;
    }
    budgetedMessages = olderMessages.slice(dropIdx);
    logger.info('Context compaction: truncated older messages for prompt budget', {
      original: olderMessages.length,
      truncated: budgetedMessages.length,
      tokensOriginal: totalTokens,
    });
  }

  const lines: string[] = [
    'You are summarizing a conversation to free context window space.',
    'Provide a concise bullet-point summary of the conversation below.',
    'Include: key topics discussed, decisions made, files modified, code written,',
    'tool calls executed and their results, and current task state.',
    'Be terse — each bullet should be one line. Omit pleasantries and filler.',
    '',
    '--- CONVERSATION TO SUMMARIZE ---',
    '',
  ];

  for (const msg of budgetedMessages) {
    const role = msg.role === 'tool' ? 'tool-result' : msg.role;
    const text = extractText(msg.content);
    if (text.trim()) {
      lines.push(`[${role}]: ${text.trim()}`);
      lines.push('');
    }
  }

  lines.push('--- END OF CONVERSATION ---');
  lines.push('');
  lines.push('Provide the summary now:');

  return lines.join('\n');
}

/**
 * compactMessages — Summarize older messages and return a compacted message list.
 *
 * The new message list contains:
 *   1. A user/assistant exchange encoding the summary of older context
 *   2. The last N messages verbatim
 *
 * The summary is encoded as a user/assistant pair so it fits within the
 * ProviderMessage type constraints (no 'system' role). The caller (conversation.ts)
 * may additionally inject the summary as an internal system message for display.
 */
export async function compactMessages(opts: CompactionOptions): Promise<CompactionResult> {
  const {
    registry,
    modelId,
    messages,
    keepRecentMessages = 10,
    trigger = 'manual',
  } = opts;

  const tokensBeforeEstimate = estimateConversationTokens(messages);

  const { recentMessages, olderMessages } = partitionMessages(
    messages,
    keepRecentMessages,
  );

  let summary = '';
  let newMessages: ProviderMessage[];

  if (olderMessages.length === 0) {
    // Nothing to summarize
    summary = '(No older messages to summarize.)';
    newMessages = messages;
    logger.info('Context compaction: no older messages to summarize, skipping LLM call');
  } else {
    const prompt = buildSummarizationPrompt(olderMessages);

    let provider: LLMProvider;
    try {
      provider = registry.getForModel(modelId);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      throw new Error(`Context compaction: failed to get provider for model '${modelId}': ${msg}`);
    }

    logger.info('Context compaction: requesting summary from LLM', {
      modelId,
      olderMessageCount: olderMessages.length,
      recentMessageCount: recentMessages.length,
      tokensBeforeEstimate,
    });

    const response = await provider.chat({
      messages: [{ role: 'user', content: prompt }],
      model: modelId,
    });

    summary = response.content?.trim() ?? '';
    if (!summary) {
      throw new Error('Context compaction: LLM returned empty summary');
    }

    // Build the compacted message list.
    // Encode the summary as a user/assistant pair so it fits ProviderMessage constraints.
    const summaryUserMsg: ProviderMessage = {
      role: 'user',
      content: '[Context compacted — summary of earlier conversation follows]',
    };
    const summaryAssistantMsg: ProviderMessage = {
      role: 'assistant',
      content: `[Summary of compacted context]\n\n${summary}`,
    };

    newMessages = [
      summaryUserMsg,
      summaryAssistantMsg,
      ...recentMessages,
    ];
  }

  const tokensAfterEstimate = estimateConversationTokens(newMessages);

  const event: CompactionEvent = {
    timestamp: Date.now(),
    messagesBeforeCompaction: messages.length,
    messagesAfterCompaction: newMessages.length,
    tokensBeforeEstimate,
    tokensAfterEstimate,
    modelId,
    trigger,
  };

  compactionEvents.push(event);
  if (compactionEvents.length > 50) compactionEvents.shift();

  logger.info('Context compaction: complete', {
    trigger,
    modelId,
    messagesBeforeCompaction: event.messagesBeforeCompaction,
    messagesAfterCompaction: event.messagesAfterCompaction,
    tokensBeforeEstimate: event.tokensBeforeEstimate,
    tokensAfterEstimate: event.tokensAfterEstimate,
    tokensSaved: event.tokensBeforeEstimate - event.tokensAfterEstimate,
  });

  return { messages: newMessages, summary, tokensBeforeEstimate, tokensAfterEstimate, event };
}

/**
 * checkAndCompact — Check if context usage exceeds threshold and compact if so.
 * Returns the compaction result if compaction was performed, null otherwise.
 */
export async function checkAndCompact(
  autoOpts: AutoCompactOptions,
  compactionOpts: Omit<CompactionOptions, 'trigger'>,
): Promise<CompactionResult | null> {
  if (!shouldAutoCompact(autoOpts)) return null;
  return compactMessages({ ...compactionOpts, trigger: 'auto' });
}
