import type {
  OperatorContractManifest,
  PeerContractManifest,
} from '../src/types/foundation-contract.ts';

export function renderFoundationClientTypes(
  _operatorContract: OperatorContractManifest,
  _peerContract: PeerContractManifest,
): string {
  return [
    '// Generated by scripts/export-foundation-artifacts.ts. Do not edit manually.',
    '',
    "export type {",
    "  OperatorEventPayload,",
    "  OperatorEventPayloadMap,",
    "  OperatorMethodInput,",
    "  OperatorMethodInputMap,",
    "  OperatorMethodOutput,",
    "  OperatorMethodOutputMap,",
    "  OperatorStreamMethodId,",
    "  OperatorTypedEventId,",
    "  OperatorTypedMethodId,",
    "  PeerEndpointInput,",
    "  PeerEndpointInputMap,",
    "  PeerEndpointOutput,",
    "  PeerEndpointOutputMap,",
    "  PeerTypedEndpointId,",
    "  RuntimeDomainEventPayload,",
    "  RuntimeDomainEventPayloadMap,",
    "  RuntimeDomainEventType,",
    "  RuntimeEventTypedDomain,",
    "} from '@pellux/goodvibes-sdk-beta/contracts';",
  ].join('\n');
}
