import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

try {
  const pkg = JSON.parse(readFileSync(join(process.cwd(), 'package.json'), 'utf8'));
  const version = pkg.version;
  const content = `// Generated by scripts/prebuild.ts\nexport const VERSION = '${version}';\n`;
  writeFileSync(join(process.cwd(), 'src/version.ts'), content);
} catch (error) {
  console.error('Failed to generate src/version.ts:', error);
  process.exit(1);
}
