export const GLYPHS = {
  frame: {
    topLeft: '┌',
    topRight: '┐',
    bottomLeft: '└',
    bottomRight: '┘',
    horizontal: '─',
    vertical: '│',
    teeLeft: '├',
    teeRight: '┤',
    teeTop: '┬',
    teeBottom: '┴',
    cross: '┼',
  },
  surface: {
    top: '▄',
    bottom: '▀',
    cursor: '█',
    altCursor: '▌',
  },
  navigation: {
    selected: '▸',
    collapsed: '▸',
    expanded: '▾',
    up: '↑',
    down: '↓',
    moreAbove: '▲',
    moreBelow: '▼',
    next: '→',
    back: '←',
    pipeSeparator: '│',
  },
  status: {
    success: '✓',
    failure: '✕',
    pending: '•',
    active: '●',
    idle: '○',
    info: '•',
    blocked: '⊘',
    skipped: '◇',
    review: '◈',
    retry: '↻',
    handoff: '⇢',
    reference: '↗',
    partial: '◐',
    dualPane: '◆',
    star: '★',
  },
  meter: {
    filled: '█',
    medium: '▓',
    light: '▒',
    empty: '░',
    spark: ['▁', '▂', '▃', '▄', '▅', '▆', '▇', '█'],
  },
} as const;

export const UI_TONES = {
  fg: {
    primary: '#e2e8f0',
    secondary: '#cbd5e1',
    muted: '#94a3b8',
    dim: '#475569',
    inverse: '#0f172a',
  },
  bg: {
    base: '#11131a',
    surface: '#161a22',
    title: '#0f172a',
    section: '#18202b',
    summary: '#1b2430',
    selected: '#223049',
    input: '#1e293b',
    warning: '#2b2116',
    error: '#2a161b',
    success: '#14241b',
  },
  state: {
    info: '#38bdf8',
    good: '#22c55e',
    warn: '#f59e0b',
    bad: '#ef4444',
    blocked: '#f97316',
    active: '#60a5fa',
  },
  accent: {
    browser: '#7dd3fc',
    control: '#22d3ee',
    inspector: '#c4b5fd',
    workflow: '#fbbf24',
    conversation: '#93c5fd',
  },
} as const;

export type UiGlyphRegistry = typeof GLYPHS;
