export type MaybeResponse = Response | Promise<Response>;

export interface DaemonApiRouteHandlers {
  getStatus(): MaybeResponse;
  getCurrentAuth(req: Request): MaybeResponse;
  getReview(): MaybeResponse;
  getIntegrationSession(): MaybeResponse;
  getIntegrationTasks(): MaybeResponse;
  getIntegrationAutomation(): MaybeResponse;
  getIntegrationSessions(): MaybeResponse;
  createSharedSession(req: Request): MaybeResponse;
  getControlPlaneSnapshot(): MaybeResponse;
  getOperatorContract(): MaybeResponse;
  getControlPlaneWeb(): MaybeResponse;
  getControlPlaneRecentEvents(limit: number): MaybeResponse;
  getControlPlaneMessages(): MaybeResponse;
  getControlPlaneClients(): MaybeResponse;
  getTelemetrySnapshot(req: Request): MaybeResponse;
  getTelemetryEvents(req: Request): MaybeResponse;
  getTelemetryErrors(req: Request): MaybeResponse;
  getTelemetryTraces(req: Request): MaybeResponse;
  getTelemetryMetrics(req: Request): MaybeResponse;
  createTelemetryEventStream(req: Request): MaybeResponse;
  getTelemetryOtlpTraces(req: Request): MaybeResponse;
  getTelemetryOtlpLogs(req: Request): MaybeResponse;
  getTelemetryOtlpMetrics(req: Request): MaybeResponse;
  getGatewayMethods(url: URL): MaybeResponse;
  getGatewayEvents(url: URL): MaybeResponse;
  getGatewayMethod(methodId: string): MaybeResponse;
  invokeGatewayMethod(methodId: string, req: Request): MaybeResponse;
  createControlPlaneEventStream(req: Request): MaybeResponse;
  getAutomationJobs(): MaybeResponse;
  postAutomationJob(req: Request): MaybeResponse;
  getAutomationRuns(): MaybeResponse;
  getAutomationRun(runId: string): MaybeResponse;
  getAutomationHeartbeat(): MaybeResponse;
  postAutomationHeartbeat(req: Request): MaybeResponse;
  automationRunAction(runId: string, action: 'cancel' | 'retry', req: Request): MaybeResponse;
  patchAutomationJob(jobId: string, req: Request): MaybeResponse;
  deleteAutomationJob(jobId: string): MaybeResponse;
  setAutomationJobEnabled(jobId: string, enabled: boolean): MaybeResponse;
  runAutomationJobNow(jobId: string): MaybeResponse;
  getDeliveries(): MaybeResponse;
  getDelivery(deliveryId: string): MaybeResponse;
  getRoutesSnapshot(): MaybeResponse;
  getSurfaces(): MaybeResponse;
  getChannelAccounts(): MaybeResponse;
  getChannelSurfaceAccounts(surface: string): MaybeResponse;
  getChannelAccount(surface: string, accountId: string): MaybeResponse;
  postChannelAccountAction(surface: string, accountId: string | null, action: string, req: Request): MaybeResponse;
  getChannelSetupSchema(surface: string, url: URL): MaybeResponse;
  getChannelDoctor(surface: string, url: URL): MaybeResponse;
  getChannelRepairActions(surface: string, url: URL): MaybeResponse;
  getChannelLifecycle(surface: string, url: URL): MaybeResponse;
  postChannelLifecycleMigrate(surface: string, req: Request): MaybeResponse;
  getChannelCapabilities(): MaybeResponse;
  getChannelSurfaceCapabilities(surface: string): MaybeResponse;
  getChannelTools(): MaybeResponse;
  getChannelSurfaceTools(surface: string): MaybeResponse;
  getChannelAgentTools(): MaybeResponse;
  getChannelSurfaceAgentTools(surface: string): MaybeResponse;
  postChannelTool(surface: string, toolId: string, req: Request): MaybeResponse;
  getChannelActions(): MaybeResponse;
  getChannelSurfaceActions(surface: string): MaybeResponse;
  postChannelAction(surface: string, actionId: string, req: Request): MaybeResponse;
  postChannelResolveTarget(surface: string, req: Request): MaybeResponse;
  postChannelAuthorize(surface: string, req: Request): MaybeResponse;
  postChannelAllowlistResolve(surface: string, req: Request): MaybeResponse;
  postChannelAllowlistEdit(surface: string, req: Request): MaybeResponse;
  getChannelPolicies(): MaybeResponse;
  postChannelPolicy(surface: string, req: Request): MaybeResponse;
  getChannelPolicyAudit(limit: number): MaybeResponse;
  getChannelStatus(): MaybeResponse;
  getChannelDirectory(surface: string, url: URL): MaybeResponse;
  getWatchers(): MaybeResponse;
  postWatcher(req: Request): MaybeResponse;
  patchWatcher(watcherId: string, req: Request): MaybeResponse;
  watcherAction(watcherId: string, action: 'start' | 'stop' | 'run'): MaybeResponse;
  deleteWatcher(watcherId: string): MaybeResponse;
  getServiceStatus(): MaybeResponse;
  installService(): MaybeResponse;
  startService(): MaybeResponse;
  stopService(): MaybeResponse;
  restartService(): MaybeResponse;
  uninstallService(): MaybeResponse;
  getRouteBindings(): MaybeResponse;
  postRouteBinding(req: Request): MaybeResponse;
  patchRouteBinding(bindingId: string, req: Request): MaybeResponse;
  deleteRouteBinding(bindingId: string): MaybeResponse;
  getApprovals(): MaybeResponse;
  approvalAction(approvalId: string, action: 'claim' | 'approve' | 'deny' | 'cancel', req: Request): MaybeResponse;
  getRemote(): MaybeResponse;
  getRemotePairRequests(): MaybeResponse;
  approveRemotePairRequest(requestId: string, req: Request): MaybeResponse;
  rejectRemotePairRequest(requestId: string, req: Request): MaybeResponse;
  getRemotePeers(): MaybeResponse;
  rotateRemotePeerToken(peerId: string, req: Request): MaybeResponse;
  revokeRemotePeerToken(peerId: string, req: Request): MaybeResponse;
  disconnectRemotePeer(peerId: string, req: Request): MaybeResponse;
  getRemoteWork(): MaybeResponse;
  invokeRemotePeer(peerId: string, req: Request): MaybeResponse;
  cancelRemoteWork(workId: string, req: Request): MaybeResponse;
  getRemoteNodeHostContract(): MaybeResponse;
  getHealth(): MaybeResponse;
  getAccounts(): MaybeResponse;
  getProviders(): MaybeResponse;
  getProvider(providerId: string): MaybeResponse;
  getProviderUsage(providerId: string): MaybeResponse;
  getSettings(): MaybeResponse;
  getContinuity(): MaybeResponse;
  getWorktrees(): MaybeResponse;
  getIntelligence(): MaybeResponse;
  getMemoryDoctor(): MaybeResponse;
  getMemoryVectorStats(): MaybeResponse;
  postMemoryVectorRebuild(req: Request): MaybeResponse;
  postMemoryEmbeddingDefault(req: Request): MaybeResponse;
  getKnowledgeStatus(): MaybeResponse;
  getKnowledgeSources(url: URL): MaybeResponse;
  getKnowledgeNodes(url: URL): MaybeResponse;
  getKnowledgeIssues(url: URL): MaybeResponse;
  getKnowledgeItem(id: string): MaybeResponse;
  getKnowledgeConnectors(): MaybeResponse;
  getKnowledgeConnector(id: string): MaybeResponse;
  getKnowledgeConnectorDoctor(id: string): MaybeResponse;
  getKnowledgeProjectionTargets(url: URL): MaybeResponse;
  getKnowledgeGraphqlSchema(): MaybeResponse;
  getKnowledgeExtractions(url: URL): MaybeResponse;
  getKnowledgeUsage(url: URL): MaybeResponse;
  getKnowledgeCandidates(url: URL): MaybeResponse;
  getKnowledgeCandidate(id: string): MaybeResponse;
  getKnowledgeReports(url: URL): MaybeResponse;
  getKnowledgeReport(id: string): MaybeResponse;
  getKnowledgeExtraction(id: string): MaybeResponse;
  getKnowledgeSourceExtraction(id: string): MaybeResponse;
  getKnowledgeJobs(): MaybeResponse;
  getKnowledgeJob(jobId: string): MaybeResponse;
  getKnowledgeJobRuns(url: URL): MaybeResponse;
  getKnowledgeSchedules(url: URL): MaybeResponse;
  getKnowledgeSchedule(id: string): MaybeResponse;
  postKnowledgeIngestUrl(req: Request): MaybeResponse;
  postKnowledgeIngestArtifact(req: Request): MaybeResponse;
  postKnowledgeImportBookmarks(req: Request): MaybeResponse;
  postKnowledgeImportUrls(req: Request): MaybeResponse;
  postKnowledgeIngestConnector(req: Request): MaybeResponse;
  postKnowledgeSearch(req: Request): MaybeResponse;
  postKnowledgePacket(req: Request): MaybeResponse;
  postKnowledgeDecideCandidate(id: string, req: Request): MaybeResponse;
  postKnowledgeRunJob(jobId: string, req: Request): MaybeResponse;
  postKnowledgeLint(req: Request): MaybeResponse;
  postKnowledgeReindex(req: Request): MaybeResponse;
  postKnowledgeSaveSchedule(req: Request): MaybeResponse;
  deleteKnowledgeSchedule(id: string, req: Request): MaybeResponse;
  postKnowledgeSetScheduleEnabled(id: string, req: Request): MaybeResponse;
  postKnowledgeRenderProjection(req: Request): MaybeResponse;
  postKnowledgeMaterializeProjection(req: Request): MaybeResponse;
  executeKnowledgeGraphql(req: Request): MaybeResponse;
  getVoiceStatus(): MaybeResponse;
  getVoiceProviders(): MaybeResponse;
  getVoiceVoices(url: URL): MaybeResponse;
  postVoiceTts(req: Request): MaybeResponse;
  postVoiceStt(req: Request): MaybeResponse;
  postVoiceRealtimeSession(req: Request): MaybeResponse;
  getWebSearchProviders(): MaybeResponse;
  postWebSearch(req: Request): MaybeResponse;
  getArtifacts(): MaybeResponse;
  postArtifact(req: Request): MaybeResponse;
  getArtifact(artifactId: string): MaybeResponse;
  getArtifactContent(artifactId: string, req: Request): MaybeResponse;
  getMediaProviders(): MaybeResponse;
  postMediaAnalyze(req: Request): MaybeResponse;
  postMediaTransform(req: Request): MaybeResponse;
  postMediaGenerate(req: Request): MaybeResponse;
  getMultimodalStatus(): MaybeResponse;
  getMultimodalProviders(): MaybeResponse;
  postMultimodalAnalyze(req: Request): MaybeResponse;
  postMultimodalPacket(req: Request): MaybeResponse;
  postMultimodalWriteback(req: Request): MaybeResponse;
  getLocalAuth(): MaybeResponse;
  postLocalAuthUser(req: Request): MaybeResponse;
  deleteLocalAuthUser(username: string): MaybeResponse;
  postLocalAuthPassword(username: string, req: Request): MaybeResponse;
  deleteLocalAuthSession(sessionId: string): MaybeResponse;
  deleteBootstrapFile(): MaybeResponse;
  getPanels(): MaybeResponse;
  postPanelOpen(req: Request): MaybeResponse;
  getEvents(req: Request): MaybeResponse;
  getConfig(): MaybeResponse;
  postConfig(req: Request): MaybeResponse;
  postTask(req: Request): MaybeResponse;
  getSharedSession(sessionId: string): MaybeResponse;
  closeSharedSession(sessionId: string): MaybeResponse;
  reopenSharedSession(sessionId: string): MaybeResponse;
  getSharedSessionMessages(sessionId: string, url: URL): MaybeResponse;
  getSharedSessionInputs(sessionId: string, url: URL): MaybeResponse;
  postSharedSessionMessage(sessionId: string, req: Request): MaybeResponse;
  postSharedSessionSteer(sessionId: string, req: Request): MaybeResponse;
  postSharedSessionFollowUp(sessionId: string, req: Request): MaybeResponse;
  cancelSharedSessionInput(sessionId: string, inputId: string): MaybeResponse;
  getRuntimeTask(taskId: string): MaybeResponse;
  runtimeTaskAction(taskId: string, action: 'cancel' | 'retry', req: Request): MaybeResponse;
  getTaskStatus(agentId: string): MaybeResponse;
  getSchedules(): MaybeResponse;
  postSchedule(req: Request): MaybeResponse;
  deleteSchedule(scheduleId: string): MaybeResponse;
  setScheduleEnabled(scheduleId: string, enabled: boolean): MaybeResponse;
  runScheduleNow(scheduleId: string): MaybeResponse;
}
