export type MaybeResponse = Response | Promise<Response>;

export interface DaemonApiRouteHandlers {
  getStatus(): MaybeResponse;
  getReview(): MaybeResponse;
  getIntegrationSession(): MaybeResponse;
  getIntegrationTasks(): MaybeResponse;
  getIntegrationAutomation(): MaybeResponse;
  getIntegrationSessions(): MaybeResponse;
  createSharedSession(req: Request): MaybeResponse;
  getControlPlaneSnapshot(): MaybeResponse;
  getControlPlaneWeb(): MaybeResponse;
  getControlPlaneRecentEvents(limit: number): MaybeResponse;
  getControlPlaneMessages(): MaybeResponse;
  getControlPlaneClients(): MaybeResponse;
  getGatewayMethods(url: URL): MaybeResponse;
  getGatewayMethod(methodId: string): MaybeResponse;
  invokeGatewayMethod(methodId: string, req: Request): MaybeResponse;
  createControlPlaneEventStream(req: Request): MaybeResponse;
  getAutomationJobs(): MaybeResponse;
  postAutomationJob(req: Request): MaybeResponse;
  getAutomationRuns(): MaybeResponse;
  getAutomationRun(runId: string): MaybeResponse;
  getAutomationHeartbeat(): MaybeResponse;
  postAutomationHeartbeat(req: Request): MaybeResponse;
  automationRunAction(runId: string, action: 'cancel' | 'retry', req: Request): MaybeResponse;
  patchAutomationJob(jobId: string, req: Request): MaybeResponse;
  deleteAutomationJob(jobId: string): MaybeResponse;
  setAutomationJobEnabled(jobId: string, enabled: boolean): MaybeResponse;
  runAutomationJobNow(jobId: string): MaybeResponse;
  getDeliveries(): MaybeResponse;
  getDelivery(deliveryId: string): MaybeResponse;
  getRoutesSnapshot(): MaybeResponse;
  getSurfaces(): MaybeResponse;
  getChannelAccounts(): MaybeResponse;
  getChannelSurfaceAccounts(surface: string): MaybeResponse;
  getChannelAccount(surface: string, accountId: string): MaybeResponse;
  postChannelAccountAction(surface: string, accountId: string | null, action: string, req: Request): MaybeResponse;
  getChannelCapabilities(): MaybeResponse;
  getChannelSurfaceCapabilities(surface: string): MaybeResponse;
  getChannelTools(): MaybeResponse;
  getChannelSurfaceTools(surface: string): MaybeResponse;
  getChannelAgentTools(): MaybeResponse;
  getChannelSurfaceAgentTools(surface: string): MaybeResponse;
  postChannelTool(surface: string, toolId: string, req: Request): MaybeResponse;
  getChannelActions(): MaybeResponse;
  getChannelSurfaceActions(surface: string): MaybeResponse;
  postChannelAction(surface: string, actionId: string, req: Request): MaybeResponse;
  postChannelResolveTarget(surface: string, req: Request): MaybeResponse;
  postChannelAuthorize(surface: string, req: Request): MaybeResponse;
  getChannelPolicies(): MaybeResponse;
  postChannelPolicy(surface: string, req: Request): MaybeResponse;
  getChannelPolicyAudit(limit: number): MaybeResponse;
  getChannelStatus(): MaybeResponse;
  getChannelDirectory(surface: string, url: URL): MaybeResponse;
  getWatchers(): MaybeResponse;
  postWatcher(req: Request): MaybeResponse;
  patchWatcher(watcherId: string, req: Request): MaybeResponse;
  watcherAction(watcherId: string, action: 'start' | 'stop' | 'run'): MaybeResponse;
  deleteWatcher(watcherId: string): MaybeResponse;
  getServiceStatus(): MaybeResponse;
  installService(): MaybeResponse;
  startService(): MaybeResponse;
  stopService(): MaybeResponse;
  restartService(): MaybeResponse;
  uninstallService(): MaybeResponse;
  getRouteBindings(): MaybeResponse;
  postRouteBinding(req: Request): MaybeResponse;
  patchRouteBinding(bindingId: string, req: Request): MaybeResponse;
  deleteRouteBinding(bindingId: string): MaybeResponse;
  getApprovals(): MaybeResponse;
  approvalAction(approvalId: string, action: 'claim' | 'approve' | 'deny' | 'cancel', req: Request): MaybeResponse;
  getRemote(): MaybeResponse;
  getRemotePairRequests(): MaybeResponse;
  approveRemotePairRequest(requestId: string, req: Request): MaybeResponse;
  rejectRemotePairRequest(requestId: string, req: Request): MaybeResponse;
  getRemotePeers(): MaybeResponse;
  rotateRemotePeerToken(peerId: string, req: Request): MaybeResponse;
  revokeRemotePeerToken(peerId: string, req: Request): MaybeResponse;
  disconnectRemotePeer(peerId: string, req: Request): MaybeResponse;
  getRemoteWork(): MaybeResponse;
  invokeRemotePeer(peerId: string, req: Request): MaybeResponse;
  cancelRemoteWork(workId: string, req: Request): MaybeResponse;
  getRemoteNodeHostContract(): MaybeResponse;
  getHealth(): MaybeResponse;
  getAccounts(): MaybeResponse;
  getSettings(): MaybeResponse;
  getContinuity(): MaybeResponse;
  getWorktrees(): MaybeResponse;
  getIntelligence(): MaybeResponse;
  getMemoryDoctor(): MaybeResponse;
  getMemoryVectorStats(): MaybeResponse;
  postMemoryVectorRebuild(req: Request): MaybeResponse;
  postMemoryEmbeddingDefault(req: Request): MaybeResponse;
  getVoiceStatus(): MaybeResponse;
  getVoiceProviders(): MaybeResponse;
  getVoiceVoices(url: URL): MaybeResponse;
  postVoiceTts(req: Request): MaybeResponse;
  postVoiceStt(req: Request): MaybeResponse;
  postVoiceRealtimeSession(req: Request): MaybeResponse;
  getMediaProviders(): MaybeResponse;
  postMediaAnalyze(req: Request): MaybeResponse;
  postMediaTransform(req: Request): MaybeResponse;
  postMediaGenerate(req: Request): MaybeResponse;
  getLocalAuth(): MaybeResponse;
  postLocalAuthUser(req: Request): MaybeResponse;
  deleteLocalAuthUser(username: string): MaybeResponse;
  postLocalAuthPassword(username: string, req: Request): MaybeResponse;
  deleteLocalAuthSession(sessionId: string): MaybeResponse;
  deleteBootstrapFile(): MaybeResponse;
  getPanels(): MaybeResponse;
  postPanelOpen(req: Request): MaybeResponse;
  getEvents(req: Request): MaybeResponse;
  getConfig(): MaybeResponse;
  postConfig(req: Request): MaybeResponse;
  postTask(req: Request): MaybeResponse;
  getSharedSession(sessionId: string): MaybeResponse;
  closeSharedSession(sessionId: string): MaybeResponse;
  reopenSharedSession(sessionId: string): MaybeResponse;
  getSharedSessionMessages(sessionId: string, url: URL): MaybeResponse;
  postSharedSessionMessage(sessionId: string, req: Request): MaybeResponse;
  getRuntimeTask(taskId: string): MaybeResponse;
  runtimeTaskAction(taskId: string, action: 'cancel' | 'retry', req: Request): MaybeResponse;
  getTaskStatus(agentId: string): MaybeResponse;
  getSchedules(): MaybeResponse;
  postSchedule(req: Request): MaybeResponse;
  deleteSchedule(scheduleId: string): MaybeResponse;
  setScheduleEnabled(scheduleId: string, enabled: boolean): MaybeResponse;
  runScheduleNow(scheduleId: string): MaybeResponse;
}
